package pe.civimoto.usuario;

import android.Manifest;
import android.app.Activity;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.location.Location;
import android.location.LocationListener;
import android.location.LocationManager;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.Gravity;
import android.view.View;
import android.webkit.JavascriptInterface;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.*;
import org.json.JSONArray;
import org.json.JSONObject;

public class FlowActivity extends Activity implements RealtimeBridge.Listener {
    private final int GOLD=Color.rgb(255,190,0), GOLD2=Color.rgb(255,220,90), BLACK=Color.rgb(5,6,8), PANEL=Color.rgb(18,20,24), PANEL2=Color.rgb(29,31,37), MUTED=Color.rgb(176,180,190), RED=Color.rgb(235,65,65), GREEN=Color.rgb(35,190,105);
    private final Handler h=new Handler(Looper.getMainLooper());
    private Backend backend; private RealtimeBridge realtime; private CiviAlert alerts;
    private LinearLayout body; private WebView map; private LocationManager lm; private LocationListener ll; private Runnable poller;
    private String tripId,driverId,lastStatus="",payment="efectivo"; private double lat=-12.0464,lng=-77.0428,dlat=-12.0564,dlng=-77.0228; private boolean destReady=false;
    private TextView tripState,driverState,fareState,connection;

    int dp(int v){return(int)(v*getResources().getDisplayMetrics().density);}
    GradientDrawable shape(int c,int r,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));if(stroke>0)g.setStroke(dp(stroke),GOLD);return g;}
    GradientDrawable gold(){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{GOLD2,GOLD,Color.rgb(255,158,0)});g.setCornerRadius(dp(16));return g;}
    TextView tx(String s,int sp,int c,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(c);if(b)t.setTypeface(null,1);t.setPadding(0,dp(3),0,dp(3));return t;}
    ImageView logo(int s){ImageView i=new ImageView(this);i.setImageResource(R.drawable.logo_civimoto);i.setScaleType(ImageView.ScaleType.CENTER_CROP);i.setBackground(shape(Color.BLACK,22,1));i.setClipToOutline(true);i.setLayoutParams(new LinearLayout.LayoutParams(dp(s),dp(s)));return i;}
    EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(MUTED);e.setTextColor(Color.WHITE);e.setSingleLine(true);e.setPadding(dp(14),dp(11),dp(14),dp(11));e.setBackground(shape(PANEL2,14,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(54));lp.setMargins(0,dp(5),0,dp(5));e.setLayoutParams(lp);return e;}
    Button btn(String s,boolean primary){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(15);b.setTypeface(null,1);b.setTextColor(primary?Color.BLACK:Color.WHITE);b.setBackground(primary?gold():shape(PANEL2,16,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(54));lp.setMargins(0,dp(5),0,dp(5));b.setLayoutParams(lp);return b;}
    LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(15),dp(16),dp(15));c.setBackground(shape(PANEL,20,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(7),0,dp(7));c.setLayoutParams(lp);return c;}

    @Override public void onCreate(Bundle b){super.onCreate(b);backend=new Backend(this);alerts=new CiviAlert(this);requestPermissionsNeeded();showSplash();h.postDelayed(()->backend.bootstrap(new Backend.Callback(){public void ok(Object v){if(backend.hasSession())backend.resume("usuario",new Backend.Callback(){public void ok(Object x){screenHome();}public void error(String m){screenLogin();}});else screenLogin();}public void error(String m){screenLogin();toast("Servidor: "+m);}}),900);}

    void showSplash(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setGravity(Gravity.CENTER);r.setPadding(dp(28),dp(28),dp(28),dp(28));r.setBackgroundColor(BLACK);r.addView(logo(260));TextView n=tx("CiviMoto",48,Color.WHITE,true);n.setGravity(Gravity.CENTER);r.addView(n);TextView t=tx("Tu destino, nuestra ruta",19,GOLD2,true);t.setGravity(Gravity.CENTER);r.addView(t);TextView s=tx("PASAJERO · EXPERIENCIA PREMIUM",12,MUTED,true);s.setGravity(Gravity.CENTER);s.setPadding(0,dp(18),0,0);r.addView(s);setContentView(r);}

    void shell(String title,String subtitle,int step){stopPollingOnly();ScrollView sc=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(14),dp(14),dp(14),dp(70));root.setBackgroundColor(BLACK);sc.addView(root);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.addView(logo(62));LinearLayout ht=new LinearLayout(this);ht.setOrientation(LinearLayout.VERTICAL);ht.setPadding(dp(11),0,0,0);ht.addView(tx(title,25,Color.WHITE,true));ht.addView(tx(subtitle,12,GOLD2,false));head.addView(ht,new LinearLayout.LayoutParams(0,-2,1));TextView badge=tx(step+" / 6",12,GOLD2,true);badge.setPadding(dp(10),dp(7),dp(10),dp(7));badge.setBackground(shape(PANEL2,18,1));head.addView(badge);root.addView(head);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(0,dp(12),0,0);root.addView(body);setContentView(sc);}

    void screenLogin(){shell("CiviMoto Pasajero","Pantalla 1 · Iniciar sesión",1);LinearLayout c=card();c.addView(tx("Bienvenido",24,Color.WHITE,true));c.addView(tx("Ingresa a tu cuenta exclusiva de CiviMoto.",13,MUTED,false));EditText email=input("Correo electrónico"),pass=input("Contraseña");pass.setInputType(0x81);c.addView(email);c.addView(pass);Button login=btn("Iniciar sesión",true),register=btn("Crear una cuenta",false);c.addView(login);c.addView(register);body.addView(c);login.setOnClickListener(v->{login.setEnabled(false);backend.login(email.getText().toString(),pass.getText().toString(),"usuario",new Backend.Callback(){public void ok(Object x){screenHome();}public void error(String m){login.setEnabled(true);toast(m);}});});register.setOnClickListener(v->screenRegister());}

    void screenRegister(){shell("Crear cuenta","Pantalla 2 · Registro de pasajero",2);LinearLayout c=card();c.addView(tx("Regístrate en CiviMoto",23,Color.WHITE,true));EditText name=input("Nombre completo"),email=input("Correo electrónico"),phone=input("Teléfono"),pass=input("Contraseña (8+ caracteres)");pass.setInputType(0x81);c.addView(name);c.addView(email);c.addView(phone);c.addView(pass);Button create=btn("Crear cuenta y continuar",true),back=btn("Ya tengo cuenta",false);c.addView(create);c.addView(back);body.addView(c);create.setOnClickListener(v->{create.setEnabled(false);backend.register(name.getText().toString(),email.getText().toString(),pass.getText().toString(),"usuario",new Backend.Callback(){public void ok(Object x){backend.login(email.getText().toString(),pass.getText().toString(),"usuario",new Backend.Callback(){public void ok(Object y){screenHome();}public void error(String m){create.setEnabled(true);toast(m);}});}public void error(String m){create.setEnabled(true);toast(m);}});});back.setOnClickListener(v->screenLogin());}

    void screenHome(){shell("Solicitar CiviMoto","Pantalla 3 · Mapa, destino y tarifa",3);connection=tx("Conectando con central…",12,MUTED,false);body.addView(connection);map=createMap();body.addView(map,new LinearLayout.LayoutParams(-1,dp(330)));LinearLayout c=card();c.addView(tx("¿A dónde vamos?",23,Color.WHITE,true));EditText dest=input("Destino o referencia");dest.setText("Toca el mapa para elegir destino");c.addView(dest);fareState=tx("Tarifa calculada por el servidor al solicitar",14,GOLD2,true);c.addView(fareState);LinearLayout pay=new LinearLayout(this);Button cash=btn("Efectivo",false),yape=btn("Yape",false);pay.addView(cash,new LinearLayout.LayoutParams(0,dp(54),1));pay.addView(yape,new LinearLayout.LayoutParams(0,dp(54),1));c.addView(pay);Button center=btn("📍 Centrar en mi ubicación",false),request=btn("Solicitar mototaxi",true),history=btn("Historial y perfil",false);c.addView(center);c.addView(request);c.addView(history);body.addView(c);cash.setOnClickListener(v->{payment="efectivo";toast("Pago: efectivo");});yape.setOnClickListener(v->{payment="yape";toast("Pago: Yape");});center.setOnClickListener(v->{freshLocation();centerMap();});history.setOnClickListener(v->screenHistory());request.setOnClickListener(v->{if(!destReady){toast("Selecciona el destino tocando el mapa.");return;}request.setEnabled(false);try{JSONObject b=new JSONObject().put("p_origin_address","Mi ubicación actual").put("p_origin_lat",lat).put("p_origin_lng",lng).put("p_destination_address",dest.getText().toString()).put("p_destination_lat",dlat).put("p_destination_lng",dlng).put("p_payment_method",payment);backend.rpc("request_civimoto_trip",b,new Backend.Callback(){public void ok(Object x){JSONObject t=Backend.firstObject(x);if(t!=null){tripId=t.optString("id");lastStatus=t.optString("status","");}screenTracking();}public void error(String m){request.setEnabled(true);toast(m);}});}catch(Exception e){request.setEnabled(true);}});freshLocation();loadActiveAndRoute();}

    void loadActiveAndRoute(){if(!backend.hasSession())return;backend.rest("GET","trips?passenger_id=eq."+backend.getUserId()+"&status=in.(solicitado,aceptado,chofer_en_camino,chofer_llego,en_viaje)&order=requested_at.desc&limit=1&select=*",null,new Backend.Callback(){public void ok(Object x){JSONObject t=Backend.firstObject(x);if(t!=null){tripId=t.optString("id");h.postDelayed(()->screenTracking(),250);}}public void error(String m){}});}

    void screenTracking(){shell("Seguimiento en vivo","Pantalla 4 · Tu viaje paso a paso",4);connection=tx("Sincronizando en tiempo real…",12,MUTED,false);body.addView(connection);map=createMap();body.addView(map,new LinearLayout.LayoutParams(-1,dp(320)));LinearLayout c=card();tripState=tx("Buscando chofer…",22,GOLD2,true);driverState=tx("Estamos notificando a choferes cercanos.",14,MUTED,false);fareState=tx("Tarifa: —",15,Color.WHITE,true);c.addView(tripState);c.addView(driverState);c.addView(fareState);Button share=btn("Compartir viaje",false),cancel=btn("Cancelar viaje",false),paymentScreen=btn("Ver método de pago",true);c.addView(share);c.addView(cancel);c.addView(paymentScreen);body.addView(c);share.setOnClickListener(v->shareTrip());cancel.setOnClickListener(v->cancelTrip());paymentScreen.setOnClickListener(v->screenPayment());freshLocation();startRealtime();startPoller();loadTripById();}

    void screenPayment(){shell("Método de pago","Pantalla 5 · Yape o efectivo",5);LinearLayout c=card();c.addView(tx("Pago del viaje",24,Color.WHITE,true));c.addView(tx("El método elegido se mantiene asociado al viaje.",13,MUTED,false));TextView p=tx("Método actual: "+payment.toUpperCase(),20,GOLD2,true);c.addView(p);Button cash=btn("Usar efectivo",false),yape=btn("Usar Yape",true),back=btn("Volver al seguimiento",false),finish=btn("Ir a historial",false);c.addView(cash);c.addView(yape);c.addView(back);c.addView(finish);body.addView(c);cash.setOnClickListener(v->{payment="efectivo";p.setText("Método actual: EFECTIVO");alerts.event("CiviMoto","Pago en efectivo seleccionado",5101);});yape.setOnClickListener(v->{payment="yape";p.setText("Método actual: YAPE");alerts.event("CiviMoto","Yape seleccionado como método de pago",5102);});back.setOnClickListener(v->screenTracking());finish.setOnClickListener(v->screenHistory());}

    void screenHistory(){shell("Viajes y perfil","Pantalla 6 · Historial y cuenta",6);LinearLayout c=card();c.addView(tx("Tus últimos viajes",22,Color.WHITE,true));TextView list=tx("Cargando…",14,MUTED,false);c.addView(list);body.addView(c);LinearLayout p=card();p.addView(tx("Mi cuenta CiviMoto",20,Color.WHITE,true));p.addView(tx("Tus datos, viajes y sesiones son independientes de CiviTaxi.",13,MUTED,false));Button home=btn("Solicitar nuevo viaje",true),logout=btn("Cerrar sesión",false);p.addView(home);p.addView(logout);body.addView(p);home.setOnClickListener(v->screenHome());logout.setOnClickListener(v->{backend.logout();stopAll();screenLogin();});backend.rest("GET","trips?passenger_id=eq."+backend.getUserId()+"&order=requested_at.desc&limit=10&select=status,destination_address,estimated_fare,final_fare",null,new Backend.Callback(){public void ok(Object x){if(!(x instanceof JSONArray)){list.setText("Aún no tienes viajes.");return;}JSONArray a=(JSONArray)x;StringBuilder s=new StringBuilder();for(int i=0;i<a.length();i++){JSONObject t=a.optJSONObject(i);if(t!=null)s.append("• ").append(t.optString("destination_address","Destino")).append(" · ").append(statusName(t.optString("status"))).append("\n");}list.setText(s.length()==0?"Aún no tienes viajes.":s.toString().trim());}public void error(String m){list.setText("No se pudo cargar el historial.");}});}

    void loadTripById(){if(tripId==null){screenHome();return;}backend.rest("GET","trips?id=eq."+tripId+"&select=*",null,new Backend.Callback(){public void ok(Object x){JSONObject t=Backend.firstObject(x);if(t!=null)renderTrip(t);}public void error(String m){if(connection!=null)connection.setText("Reintentando conexión…");}});}
    void renderTrip(JSONObject t){String s=t.optString("status","solicitado");double f=t.optDouble("final_fare",t.optDouble("estimated_fare",0));if(tripState!=null)tripState.setText(statusName(s));if(fareState!=null)fareState.setText("Tarifa: "+(f>0?String.format("S/ %.2f",f):"calculando")+" · "+t.optString("payment_method",payment).toUpperCase());driverId=t.optString("driver_id","");if(driverState!=null)driverState.setText(driverId==null||driverId.isEmpty()||"null".equals(driverId)?"Buscando choferes cercanos…":"Chofer asignado · ubicación en vivo");if(!s.equals(lastStatus)){notifyStatus(s);lastStatus=s;}if(driverId!=null&&!driverId.isEmpty()&&!"null".equals(driverId))loadDriverLocation();if("completado".equals(s)||"cancelado".equals(s)){stopRealtime();h.postDelayed(()->screenPayment(),900);}}
    void notifyStatus(String s){if("aceptado".equals(s)||"chofer_en_camino".equals(s))alerts.event("Viaje aceptado","Tu chofer va en camino",5201);else if("chofer_llego".equals(s))alerts.event("Tu chofer llegó","Ya está esperando en el punto de recojo",5202);else if("en_viaje".equals(s))alerts.event("Viaje iniciado","Buen viaje con CiviMoto",5203);else if("completado".equals(s))alerts.event("Viaje finalizado","Gracias por usar CiviMoto",5204);else if("cancelado".equals(s))alerts.event("Viaje cancelado","La solicitud fue cancelada",5205);}
    void loadDriverLocation(){backend.rest("GET","driver_live_locations?driver_id=eq."+driverId+"&select=lat,lng",null,new Backend.Callback(){public void ok(Object x){JSONObject p=Backend.firstObject(x);if(p!=null&&map!=null)map.evaluateJavascript("setDriver("+p.optDouble("lng")+","+p.optDouble("lat")+")",null);}public void error(String m){}});}
    void cancelTrip(){if(tripId==null)return;try{backend.rpc("passenger_cancel_civimoto_trip",new JSONObject().put("p_trip_id",tripId).put("p_reason","Cancelado por pasajero"),new Backend.Callback(){public void ok(Object x){loadTripById();}public void error(String m){toast(m);}});}catch(Exception ignored){}}
    void shareTrip(){if(tripId==null){toast("No hay viaje activo.");return;}Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,"Estoy viajando con CiviMoto. Viaje "+tripId+". Tu destino, nuestra ruta.");startActivity(Intent.createChooser(i,"Compartir viaje CiviMoto"));}

    void startRealtime(){stopRealtime();realtime=new RealtimeBridge(this,backend,this);WebView w=realtime.start("cm_trips","cm_driver_live_locations","cm_passenger_notifications");w.setVisibility(View.INVISIBLE);body.addView(w,new LinearLayout.LayoutParams(1,1));}
    void startPoller(){poller=new Runnable(){public void run(){if(backend.hasSession()&&tripId!=null)loadTripById();h.postDelayed(this,4000);}};h.postDelayed(poller,4000);}
    void stopRealtime(){if(realtime!=null){realtime.stop();realtime=null;}if(poller!=null){h.removeCallbacks(poller);poller=null;}}
    void stopPollingOnly(){if(poller!=null){h.removeCallbacks(poller);poller=null;}}
    public void onRealtime(String table,String payload){if(connection!=null)connection.setText("● En tiempo real");if(table.contains("trips"))loadTripById();if(table.contains("live_locations"))loadDriverLocation();}
    public void onRealtimeStatus(String s){if(connection!=null)connection.setText("SUBSCRIBED".equals(s)?"● En tiempo real":"Sincronizando…");}

    void requestPermissionsNeeded(){if(android.os.Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},20);if(android.os.Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},21);}
    void freshLocation(){try{lm=(LocationManager)getSystemService(LOCATION_SERVICE);if(android.os.Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return;Location g=lm.getLastKnownLocation(LocationManager.GPS_PROVIDER),n=lm.getLastKnownLocation(LocationManager.NETWORK_PROVIDER),best=g!=null?g:n;if(best!=null)applyLocation(best);if(ll==null)ll=new LocationListener(){public void onLocationChanged(Location l){applyLocation(l);}public void onStatusChanged(String p,int s,Bundle b){}public void onProviderEnabled(String p){}public void onProviderDisabled(String p){}};try{lm.requestLocationUpdates(LocationManager.GPS_PROVIDER,3000,3,ll);}catch(Exception ignored){}try{lm.requestLocationUpdates(LocationManager.NETWORK_PROVIDER,4000,5,ll);}catch(Exception ignored){}}catch(Exception ignored){}}
    void applyLocation(Location l){lat=l.getLatitude();lng=l.getLongitude();centerMap();}
    void centerMap(){if(map!=null)map.evaluateJavascript("setMe("+lng+","+lat+")",null);}
    WebView createMap(){WebView w=new WebView(this);WebSettings s=w.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);w.setWebViewClient(new WebViewClient());w.addJavascriptInterface(new MapBridge(),"AndroidMap");String html="<!doctype html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'><link href='https://unpkg.com/maplibre-gl@5.6.2/dist/maplibre-gl.css' rel='stylesheet'><style>html,body,#m{margin:0;width:100%;height:100%;background:#101216}</style></head><body><div id='m'></div><script src='https://unpkg.com/maplibre-gl@5.6.2/dist/maplibre-gl.js'></script><script>let map=new maplibregl.Map({container:'m',style:'https://tiles.openfreemap.org/styles/liberty',center:[-77.0428,-12.0464],zoom:13});let me,dest,drv;function setMe(x,y){if(me)me.remove();me=new maplibregl.Marker({color:'#ffbe00'}).setLngLat([x,y]).addTo(map);map.flyTo({center:[x,y],zoom:16});}function setDriver(x,y){if(drv)drv.remove();drv=new maplibregl.Marker({color:'#111'}).setLngLat([x,y]).addTo(map);}map.on('click',e=>{if(dest)dest.remove();dest=new maplibregl.Marker({color:'#ef4040'}).setLngLat(e.lngLat).addTo(map);AndroidMap.destination(e.lngLat.lat,e.lngLat.lng);});</script></body></html>";w.loadDataWithBaseURL("https://passenger.civimoto.local/",html,"text/html","UTF-8",null);h.postDelayed(this::centerMap,1000);return w;}
    class MapBridge{@JavascriptInterface public void destination(double a,double b){runOnUiThread(()->{dlat=a;dlng=b;destReady=true;toast("Destino marcado");});}}
    String statusName(String s){if("solicitado".equals(s))return"Buscando mototaxi";if("aceptado".equals(s))return"Chofer asignado";if("chofer_en_camino".equals(s))return"Chofer en camino";if("chofer_llego".equals(s))return"Tu chofer llegó";if("en_viaje".equals(s))return"Viaje en curso";if("completado".equals(s))return"Viaje completado";if("cancelado".equals(s))return"Viaje cancelado";return s;}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    void stopAll(){stopRealtime();try{if(lm!=null&&ll!=null)lm.removeUpdates(ll);}catch(Exception ignored){}}
    @Override protected void onDestroy(){super.onDestroy();stopAll();if(alerts!=null)alerts.release();}
}
