package pe.civimoto.usuario;

import android.Manifest;
import android.app.Activity;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.location.Location;
import android.location.LocationListener;
import android.location.LocationManager;
import android.os.Build;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.Gravity;
import android.view.View;
import android.webkit.JavascriptInterface;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.*;
import org.json.JSONArray;
import org.json.JSONObject;
import java.util.ArrayList;

public class PremiumActivity extends Activity implements RealtimeBridge.Listener {
    private final int GOLD=Color.rgb(255,190,0), GOLD2=Color.rgb(255,215,70), BLACK=Color.rgb(7,8,10), PANEL=Color.rgb(18,20,24), PANEL2=Color.rgb(27,29,34), MUTED=Color.rgb(170,174,184), RED=Color.rgb(235,64,64);
    private final Handler handler=new Handler(Looper.getMainLooper());
    private Backend backend; private RealtimeBridge realtime; private CiviAlert alerts; private LinearLayout root; private WebView map;
    private TextView connection,statusText,driverText,fareText,historyText; private EditText destination;
    private Button requestBtn,cancelBtn; private String tripId,driverId,payment="efectivo",lastStatus="";
    private double lat=-12.0464,lng=-77.0428,dlat=-12.0564,dlng=-77.0228; private boolean hasDestination=false;
    private LocationManager locationManager; private LocationListener listener; private Runnable poller;

    int dp(int v){return (int)(v*getResources().getDisplayMetrics().density);}
    GradientDrawable shape(int color,int radius,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));if(stroke>0)g.setStroke(dp(stroke),GOLD);return g;}
    GradientDrawable goldButton(){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{GOLD2,GOLD,Color.rgb(255,155,0)});g.setCornerRadius(dp(16));return g;}
    TextView txt(String s,int sp,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(c);if(bold)t.setTypeface(null,1);t.setPadding(0,dp(3),0,dp(3));return t;}
    ImageView logo(int s){ImageView i=new ImageView(this);i.setImageResource(R.drawable.logo_civimoto);i.setScaleType(ImageView.ScaleType.CENTER_CROP);i.setBackground(shape(Color.BLACK,24,1));i.setClipToOutline(true);i.setLayoutParams(new LinearLayout.LayoutParams(dp(s),dp(s)));return i;}
    LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(15),dp(16),dp(15));c.setBackground(shape(PANEL,20,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(7),0,dp(7));c.setLayoutParams(lp);return c;}
    Button primary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.BLACK);b.setTextSize(15);b.setTypeface(null,1);b.setAllCaps(false);b.setBackground(goldButton());LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(54));lp.setMargins(0,dp(6),0,dp(6));b.setLayoutParams(lp);return b;}
    Button dark(String s){Button b=primary(s);b.setTextColor(Color.WHITE);b.setBackground(shape(PANEL2,16,1));return b;}
    Button danger(String s){Button b=primary(s);b.setTextColor(Color.WHITE);b.setBackground(shape(RED,16,0));return b;}
    EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setHintTextColor(MUTED);e.setTextColor(Color.WHITE);e.setSingleLine(true);e.setPadding(dp(14),dp(12),dp(14),dp(12));e.setBackground(shape(PANEL2,14,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(54));lp.setMargins(0,dp(5),0,dp(5));e.setLayoutParams(lp);return e;}
    TextView chip(String s){TextView t=txt(s,12,GOLD2,true);t.setGravity(Gravity.CENTER);t.setBackground(shape(PANEL2,20,1));t.setPadding(dp(12),dp(8),dp(12),dp(8));return t;}

    @Override public void onCreate(Bundle b){super.onCreate(b);backend=new Backend(this);alerts=new CiviAlert(this);requestPermissionsNeeded();showSplash();handler.postDelayed(()->backend.bootstrap(new Backend.Callback(){public void ok(Object v){if(backend.hasSession())backend.resume("usuario",new Backend.Callback(){public void ok(Object x){showHome();}public void error(String m){showLogin();}});else showLogin();}public void error(String m){showLogin();toast("Servidor: "+m);}}),900);}

    void showSplash(){LinearLayout s=new LinearLayout(this);s.setOrientation(LinearLayout.VERTICAL);s.setGravity(Gravity.CENTER);s.setPadding(dp(24),dp(28),dp(24),dp(28));s.setBackgroundColor(BLACK);s.addView(logo(286));TextView n=txt("CiviMoto",48,Color.WHITE,true);n.setGravity(Gravity.CENTER);s.addView(n);TextView tag=txt("Tu destino, nuestra ruta",19,GOLD2,true);tag.setGravity(Gravity.CENTER);s.addView(tag);TextView role=chip("PASAJERO  •  GPS  •  ALERTAS  •  TIEMPO REAL");LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-2,-2);rp.setMargins(0,dp(22),0,0);role.setLayoutParams(rp);s.addView(role);setContentView(s);}

    void showLogin(){ScrollView sc=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(22),dp(24),dp(22),dp(38));r.setBackgroundColor(BLACK);sc.addView(r);setContentView(sc);LinearLayout brand=new LinearLayout(this);brand.setOrientation(LinearLayout.VERTICAL);brand.setGravity(Gravity.CENTER);brand.addView(logo(160));TextView title=txt("CiviMoto",38,Color.WHITE,true);title.setGravity(Gravity.CENTER);brand.addView(title);TextView sub=txt("Bienvenido · Tu viaje, en buenas manos",15,GOLD2,true);sub.setGravity(Gravity.CENTER);brand.addView(sub);r.addView(brand);LinearLayout c=card();c.addView(txt("Inicia sesión o crea tu cuenta",21,Color.WHITE,true));c.addView(txt("CiviMoto es independiente de CiviTaxi.",12,MUTED,false));EditText name=input("Nombre completo"),email=input("Correo electrónico"),pass=input("Contraseña");pass.setInputType(0x81);c.addView(name);c.addView(email);c.addView(pass);Button login=primary("Iniciar sesión"),register=dark("Crear cuenta de pasajero");c.addView(login);c.addView(register);r.addView(c);LinearLayout f=card();f.addView(txt("Alertas de viaje",18,Color.WHITE,true));f.addView(txt("Recibirás sonido y vibración cuando el chofer acepte, llegue, inicie o termine el viaje.",14,MUTED,false));r.addView(f);login.setOnClickListener(v->{login.setEnabled(false);backend.login(email.getText().toString(),pass.getText().toString(),"usuario",new Backend.Callback(){public void ok(Object x){showHome();}public void error(String m){login.setEnabled(true);toast(m);}});});register.setOnClickListener(v->{register.setEnabled(false);backend.register(name.getText().toString(),email.getText().toString(),pass.getText().toString(),"usuario",new Backend.Callback(){public void ok(Object x){backend.login(email.getText().toString(),pass.getText().toString(),"usuario",new Backend.Callback(){public void ok(Object y){showHome();}public void error(String m){register.setEnabled(true);toast(m);}});}public void error(String m){register.setEnabled(true);toast(m);}});});}

    void showHome(){ScrollView sc=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(14),dp(14),dp(14),dp(90));root.setBackgroundColor(BLACK);sc.addView(root);setContentView(sc);LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.addView(logo(64));LinearLayout ht=new LinearLayout(this);ht.setOrientation(LinearLayout.VERTICAL);ht.setPadding(dp(11),0,0,0);ht.addView(txt("CiviMoto",28,Color.WHITE,true));connection=txt("Conectando en tiempo real…",12,MUTED,false);ht.addView(connection);h.addView(ht,new LinearLayout.LayoutParams(0,-2,1));Button out=dark("Salir");out.setLayoutParams(new LinearLayout.LayoutParams(dp(82),dp(48)));h.addView(out);root.addView(h);out.setOnClickListener(v->{backend.logout();stopRealtime();showLogin();});
        LinearLayout chips=new LinearLayout(this);chips.setGravity(Gravity.CENTER);String[] cs={"⚡ Rápido","🛡 Seguro","🔔 Alertas"};for(String s:cs){TextView x=chip(s);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);lp.setMargins(dp(3),dp(10),dp(3),dp(8));chips.addView(x,lp);}root.addView(chips);
        TextView q=txt("¿A dónde vamos?",27,Color.WHITE,true);q.setPadding(0,dp(8),0,dp(6));root.addView(q);map=createMap();map.setBackground(shape(PANEL,22,1));root.addView(map,new LinearLayout.LayoutParams(-1,dp(330)));
        LinearLayout ask=card();ask.addView(txt("Solicitar viaje",20,Color.WHITE,true));ask.addView(txt("El mapa se centra en tu GPS. Toca el mapa para marcar el destino.",13,MUTED,false));destination=input("Destino o referencia");destination.setText("Selecciona tu destino en el mapa");ask.addView(destination);fareText=txt("Tarifa: se calcula al solicitar",15,GOLD2,true);ask.addView(fareText);LinearLayout pays=new LinearLayout(this);Button cash=dark("Efectivo"),yape=dark("Yape");pays.addView(cash,new LinearLayout.LayoutParams(0,dp(52),1));pays.addView(yape,new LinearLayout.LayoutParams(0,dp(52),1));ask.addView(pays);Button locate=dark("📍 Centrar en mi ubicación");requestBtn=primary("Solicitar CiviMoto");ask.addView(locate);ask.addView(requestBtn);root.addView(ask);
        LinearLayout trip=card();trip.addView(txt("Viaje en curso",20,Color.WHITE,true));statusText=txt("Sin viaje activo",17,GOLD2,true);driverText=txt("Cuando un chofer acepte verás aquí sus datos.",14,MUTED,false);trip.addView(statusText);trip.addView(driverText);Button share=dark("Compartir viaje");cancelBtn=danger("Cancelar viaje");cancelBtn.setEnabled(false);trip.addView(share);trip.addView(cancelBtn);root.addView(trip);
        LinearLayout hist=card();hist.addView(txt("Historial de viajes",20,Color.WHITE,true));historyText=txt("Cargando…",14,MUTED,false);hist.addView(historyText);root.addView(hist);
        cash.setOnClickListener(v->{payment="efectivo";toast("Método: efectivo");});yape.setOnClickListener(v->{payment="yape";toast("Método: Yape");});locate.setOnClickListener(v->{freshLocation();if(map!=null)map.evaluateJavascript("setMe("+lng+","+lat+")",null);});requestBtn.setOnClickListener(v->requestTrip());cancelBtn.setOnClickListener(v->cancelTrip());share.setOnClickListener(v->shareTrip());freshLocation();loadTrip();loadHistory();startRealtime();startPoller();}

    void requestTrip(){if(!hasDestination){toast("Selecciona el destino tocando el mapa.");return;}requestBtn.setEnabled(false);statusText.setText("Buscando mototaxi cercano…");try{JSONObject b=new JSONObject().put("p_origin_address","Mi ubicación actual").put("p_origin_lat",lat).put("p_origin_lng",lng).put("p_destination_address",destination.getText().toString()).put("p_destination_lat",dlat).put("p_destination_lng",dlng).put("p_payment_method",payment);backend.rpc("request_civimoto_trip",b,new Backend.Callback(){public void ok(Object v){JSONObject t=Backend.firstObject(v);if(t!=null){tripId=t.optString("id");lastStatus="solicitado";renderTrip(t);}loadHistory();}public void error(String m){requestBtn.setEnabled(true);statusText.setText("No se pudo solicitar");toast(m);}});}catch(Exception e){requestBtn.setEnabled(true);}}
    void cancelTrip(){if(tripId==null)return;try{backend.rpc("passenger_cancel_civimoto_trip",new JSONObject().put("p_trip_id",tripId).put("p_reason","Cancelado por pasajero"),new Backend.Callback(){public void ok(Object v){JSONObject t=Backend.firstObject(v);if(t!=null)renderTrip(t);}public void error(String m){toast(m);}});}catch(Exception ignored){}}
    void loadTrip(){String p="trips?passenger_id=eq."+backend.getUserId()+"&status=in.(solicitado,aceptado,chofer_en_camino,chofer_llego,en_viaje)&order=requested_at.desc&limit=1&select=*";backend.rest("GET",p,null,new Backend.Callback(){public void ok(Object v){JSONObject t=Backend.firstObject(v);if(t!=null){tripId=t.optString("id");renderTrip(t);}else if(tripId==null)resetTrip();}public void error(String m){connection.setText("Sincronizando…");}});}
    void renderTrip(JSONObject t){String s=t.optString("status","solicitado");maybeAlert(s);double f=t.optDouble("final_fare",t.optDouble("estimated_fare",0));statusText.setText(statusName(s)+(f>0?"  ·  S/ "+String.format("%.2f",f):""));fareText.setText("Tarifa estimada: "+(f>0?"S/ "+String.format("%.2f",f):"—")+"  ·  "+t.optString("payment_method","efectivo").toUpperCase());driverId=t.optString("driver_id","");if(driverId!=null&&!driverId.isEmpty()&&!"null".equals(driverId)){driverText.setText("Chofer asignado · ubicación en vivo activada");loadDriverLocation();}else driverText.setText("Buscando choferes cercanos…");boolean active=!s.equals("completado")&&!s.equals("cancelado");cancelBtn.setEnabled(active&&!s.equals("en_viaje"));requestBtn.setEnabled(!active);requestBtn.setText(active?"Viaje activo":"Solicitar otro CiviMoto");if(!active){tripId=null;driverId=null;loadHistory();}}
    void maybeAlert(String s){if(s==null||s.equals(lastStatus))return;String previous=lastStatus;lastStatus=s;if("aceptado".equals(s)||("chofer_en_camino".equals(s)&&"solicitado".equals(previous)))alerts.event("¡Viaje aceptado!","Tu chofer ya va hacia tu ubicación.",5101);else if("chofer_llego".equals(s))alerts.event("Tu chofer llegó","El mototaxi está esperando en el punto de origen.",5102);else if("en_viaje".equals(s))alerts.event("Viaje iniciado","Tu recorrido CiviMoto comenzó.",5103);else if("completado".equals(s))alerts.event("Viaje finalizado","Llegaste a tu destino. Gracias por usar CiviMoto.",5104);else if("cancelado".equals(s))alerts.event("Viaje cancelado","El viaje ya no está activo.",5105);}
    void resetTrip(){statusText.setText("Sin viaje activo");driverText.setText("Listo para solicitar.");cancelBtn.setEnabled(false);requestBtn.setEnabled(true);requestBtn.setText("Solicitar CiviMoto");if(tripId==null)lastStatus="";}
    String statusName(String s){if("solicitado".equals(s))return"Buscando mototaxi";if("aceptado".equals(s))return"Chofer asignado";if("chofer_en_camino".equals(s))return"Chofer en camino";if("chofer_llego".equals(s))return"Tu chofer llegó";if("en_viaje".equals(s))return"Viaje en curso";if("completado".equals(s))return"Completado";if("cancelado".equals(s))return"Cancelado";return s;}
    void loadDriverLocation(){if(driverId==null)return;backend.rest("GET","driver_live_locations?driver_id=eq."+driverId+"&select=lat,lng,updated_at",null,new Backend.Callback(){public void ok(Object v){JSONObject p=Backend.firstObject(v);if(p!=null&&map!=null)map.evaluateJavascript("setDriver("+p.optDouble("lng")+","+p.optDouble("lat")+")",null);}public void error(String m){}});}
    void loadHistory(){backend.rest("GET","trips?passenger_id=eq."+backend.getUserId()+"&order=requested_at.desc&limit=6&select=status,destination_address,estimated_fare,final_fare",null,new Backend.Callback(){public void ok(Object v){if(!(v instanceof JSONArray)){historyText.setText("Aún no tienes viajes.");return;}JSONArray a=(JSONArray)v;StringBuilder s=new StringBuilder();for(int i=0;i<a.length();i++){JSONObject t=a.optJSONObject(i);if(t!=null)s.append("• ").append(t.optString("destination_address","Destino")).append(" · ").append(statusName(t.optString("status"))).append("\n");}historyText.setText(s.length()==0?"Aún no tienes viajes.":s.toString().trim());}public void error(String m){historyText.setText("No se pudo cargar el historial.");}});}
    void shareTrip(){if(tripId==null){toast("No hay viaje activo.");return;}Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,"Estoy viajando con CiviMoto. Viaje "+tripId+". Tu destino, nuestra ruta.");startActivity(Intent.createChooser(i,"Compartir viaje"));}

    void startRealtime(){realtime=new RealtimeBridge(this,backend,this);WebView w=realtime.start("cm_trips","cm_driver_live_locations","cm_passenger_notifications");w.setVisibility(View.INVISIBLE);root.addView(w,new LinearLayout.LayoutParams(1,1));}
    void startPoller(){poller=new Runnable(){public void run(){if(backend.hasSession())loadTrip();handler.postDelayed(this,4000);}};handler.postDelayed(poller,3000);}
    void stopRealtime(){if(realtime!=null)realtime.stop();if(poller!=null)handler.removeCallbacks(poller);try{if(locationManager!=null&&listener!=null)locationManager.removeUpdates(listener);}catch(Exception ignored){}}
    public void onRealtime(String table,String payload){connection.setText("● En tiempo real");if(table.contains("trips")){try{JSONObject p=new JSONObject(payload);JSONObject rec=p.optJSONObject("new");if(rec!=null){String id=rec.optString("id");if(tripId==null||tripId.equals(id)){tripId=id;renderTrip(rec);return;}}}catch(Exception ignored){}loadTrip();}else if(table.contains("live_locations"))loadDriverLocation();else if(table.contains("notifications"))alerts.event("CiviMoto","Tienes una nueva notificación del servicio.",5110);}
    public void onRealtimeStatus(String s){connection.setText("SUBSCRIBED".equals(s)?"● En tiempo real":"Sincronizando…");}

    void requestPermissionsNeeded(){if(Build.VERSION.SDK_INT<23)return;ArrayList<String> p=new ArrayList<>();if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){p.add(Manifest.permission.ACCESS_FINE_LOCATION);p.add(Manifest.permission.ACCESS_COARSE_LOCATION);}if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)p.add(Manifest.permission.POST_NOTIFICATIONS);if(!p.isEmpty())requestPermissions(p.toArray(new String[0]),20);}
    void freshLocation(){try{locationManager=(LocationManager)getSystemService(LOCATION_SERVICE);if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return;Location last=null;try{last=locationManager.getLastKnownLocation(LocationManager.GPS_PROVIDER);}catch(Exception ignored){}if(last==null)try{last=locationManager.getLastKnownLocation(LocationManager.NETWORK_PROVIDER);}catch(Exception ignored){}if(last!=null)applyLocation(last);if(listener==null)listener=new LocationListener(){public void onLocationChanged(Location l){applyLocation(l);}public void onStatusChanged(String p,int s,Bundle b){}public void onProviderEnabled(String p){}public void onProviderDisabled(String p){}};try{locationManager.requestLocationUpdates(LocationManager.GPS_PROVIDER,3000,3,listener);}catch(Exception ignored){}try{locationManager.requestLocationUpdates(LocationManager.NETWORK_PROVIDER,4000,4,listener);}catch(Exception ignored){}}catch(Exception ignored){}}
    void applyLocation(Location l){lat=l.getLatitude();lng=l.getLongitude();if(map!=null)map.evaluateJavascript("setMe("+lng+","+lat+")",null);}
    WebView createMap(){WebView w=new WebView(this);WebSettings s=w.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);w.setWebViewClient(new WebViewClient(){@Override public void onPageFinished(WebView v,String u){v.evaluateJavascript("setMe("+lng+","+lat+")",null);}});w.addJavascriptInterface(new MapBridge(),"AndroidMap");String html="<!doctype html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'><link href='https://unpkg.com/maplibre-gl@5.6.2/dist/maplibre-gl.css' rel='stylesheet'><style>html,body,#m{margin:0;width:100%;height:100%;background:#101216}.maplibregl-ctrl-attrib{font-size:8px}</style></head><body><div id='m'></div><script src='https://unpkg.com/maplibre-gl@5.6.2/dist/maplibre-gl.js'></script><script>let map=new maplibregl.Map({container:'m',style:'https://tiles.openfreemap.org/styles/liberty',center:[-77.0428,-12.0464],zoom:13});let me,dest,drv;function setMe(x,y){if(me)me.remove();me=new maplibregl.Marker({color:'#ffbe00'}).setLngLat([x,y]).addTo(map);map.easeTo({center:[x,y],zoom:16});}function setDriver(x,y){if(drv)drv.remove();drv=new maplibregl.Marker({color:'#111'}).setLngLat([x,y]).addTo(map);}map.on('click',e=>{if(dest)dest.remove();dest=new maplibregl.Marker({color:'#ef4040'}).setLngLat(e.lngLat).addTo(map);AndroidMap.destination(e.lngLat.lat,e.lngLat.lng);});</script></body></html>";w.loadDataWithBaseURL("https://passenger.civimoto.local/",html,"text/html","UTF-8",null);return w;}
    class MapBridge{@JavascriptInterface public void destination(double a,double b){runOnUiThread(()->{dlat=a;dlng=b;hasDestination=true;destination.setText(String.format("Destino %.5f, %.5f",a,b));});}}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    @Override protected void onDestroy(){super.onDestroy();stopRealtime();if(alerts!=null)alerts.release();}
}
