-- CiviMoto backend independiente
-- No comparte Auth, tablas ni Realtime con CiviTaxi.

create extension if not exists pgcrypto;

create type public.user_role as enum ('usuario','chofer','admin');
create type public.driver_status as enum ('pendiente','aprobado','rechazado','suspendido');
create type public.trip_status as enum ('solicitado','aceptado','chofer_en_camino','chofer_llego','en_viaje','completado','cancelado');
create type public.billing_period as enum ('semanal','mensual');
create type public.payment_status as enum ('pendiente','aprobado','rechazado');

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role public.user_role not null default 'usuario',
  full_name text not null default '',
  phone text,
  email text,
  avatar_url text,
  rating numeric(3,2) not null default 5.00 check (rating between 1 and 5),
  account_status text not null default 'activo' check (account_status in ('activo','suspendido')),
  suspended_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.drivers (
  id uuid primary key references public.profiles(id) on delete cascade,
  status public.driver_status not null default 'pendiente',
  document_number text,
  license_number text,
  is_available boolean not null default false,
  rating numeric(3,2) not null default 5.00 check (rating between 1 and 5),
  approved_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.vehicles (
  id uuid primary key default gen_random_uuid(),
  driver_id uuid not null references public.drivers(id) on delete cascade,
  plate text not null unique,
  brand text,
  model text,
  color text,
  year integer,
  photo_url text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.fares (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'Tarifa general',
  base_fare numeric(10,2) not null default 3.00,
  per_km numeric(10,2) not null default 1.50,
  per_minute numeric(10,2) not null default 0.00,
  minimum_fare numeric(10,2) not null default 5.00,
  platform_commission_percent numeric(5,2) not null default 0.00,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
insert into public.fares(name,base_fare,per_km,per_minute,minimum_fare,platform_commission_percent)
values ('Tarifa CiviMoto',3.00,1.50,0.00,5.00,0.00);

create table public.trips (
  id uuid primary key default gen_random_uuid(),
  passenger_id uuid not null references public.profiles(id),
  driver_id uuid references public.drivers(id),
  vehicle_id uuid references public.vehicles(id),
  status public.trip_status not null default 'solicitado',
  origin_address text not null,
  origin_lat double precision not null,
  origin_lng double precision not null,
  destination_address text not null,
  destination_lat double precision not null,
  destination_lng double precision not null,
  estimated_distance_km numeric(10,2),
  estimated_duration_min integer,
  estimated_fare numeric(10,2),
  final_fare numeric(10,2),
  payment_method text not null default 'efectivo' check (payment_method in ('efectivo','yape')),
  cancellation_reason text,
  requested_at timestamptz not null default now(),
  accepted_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz
);
create index trips_passenger_idx on public.trips(passenger_id, requested_at desc);
create index trips_driver_idx on public.trips(driver_id, requested_at desc);
create index trips_status_idx on public.trips(status, requested_at desc);

create table public.driver_live_locations (
  driver_id uuid primary key references public.drivers(id) on delete cascade,
  lat double precision not null,
  lng double precision not null,
  heading double precision,
  speed_kmh double precision,
  updated_at timestamptz not null default now()
);

create table public.trip_locations (
  id bigint generated by default as identity primary key,
  trip_id uuid not null references public.trips(id) on delete cascade,
  actor_id uuid not null references public.profiles(id) on delete cascade,
  lat double precision not null,
  lng double precision not null,
  heading double precision,
  speed_kmh double precision,
  created_at timestamptz not null default now()
);
create index trip_locations_trip_idx on public.trip_locations(trip_id, created_at desc);

create table public.driver_subscription_payments (
  id uuid primary key default gen_random_uuid(),
  driver_id uuid not null references public.drivers(id) on delete cascade,
  period public.billing_period not null,
  amount numeric(10,2) not null check (amount >= 0),
  payment_method text not null default 'yape' check (payment_method = 'yape'),
  operation_reference text,
  receipt_url text,
  status public.payment_status not null default 'pendiente',
  reviewed_by uuid references public.profiles(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);
create index driver_subscription_payments_idx on public.driver_subscription_payments(driver_id, created_at desc);

create table public.driver_billing (
  id boolean primary key default true check (id),
  yape_name text not null default 'CiviMoto',
  yape_phone text not null default '',
  weekly_amount numeric(10,2) not null default 0,
  monthly_amount numeric(10,2) not null default 0,
  updated_at timestamptz not null default now()
);
insert into public.driver_billing(id) values (true) on conflict do nothing;

create table public.passenger_notifications (
  id uuid primary key default gen_random_uuid(),
  passenger_id uuid not null references public.profiles(id) on delete cascade,
  title text not null default 'CiviMoto',
  body text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.driver_notifications (
  id uuid primary key default gen_random_uuid(),
  driver_id uuid not null references public.drivers(id) on delete cascade,
  title text not null default 'CiviMoto',
  body text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin');
$$;
revoke all on function private.is_admin() from public, anon, authenticated;
grant execute on function private.is_admin() to authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare r public.user_role;
begin
  r := case when new.raw_user_meta_data->>'role'='chofer' then 'chofer'::public.user_role else 'usuario'::public.user_role end;
  insert into public.profiles(id,role,full_name,email)
  values(new.id,r,coalesce(new.raw_user_meta_data->>'full_name',''),new.email)
  on conflict (id) do nothing;
  if r='chofer' then insert into public.drivers(id) values(new.id) on conflict do nothing; end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.civimoto_distance_km(lat1 double precision, lon1 double precision, lat2 double precision, lon2 double precision)
returns numeric
language sql
immutable
as $$
  select round((6371 * 2 * asin(sqrt(
    power(sin(radians(lat2-lat1)/2),2) +
    cos(radians(lat1))*cos(radians(lat2))*power(sin(radians(lon2-lon1)/2),2)
  )))::numeric,2);
$$;

create or replace function public.request_civimoto_trip(
  p_origin_address text,p_origin_lat double precision,p_origin_lng double precision,
  p_destination_address text,p_destination_lat double precision,p_destination_lng double precision,
  p_payment_method text default 'efectivo'
) returns public.trips
language plpgsql
security invoker
set search_path = public
as $$
declare d numeric; f numeric; fare_row public.fares%rowtype; out_trip public.trips%rowtype;
begin
  if auth.uid() is null then raise exception 'Debes iniciar sesión'; end if;
  if not exists(select 1 from public.profiles where id=auth.uid() and role='usuario' and account_status='activo') then raise exception 'Cuenta de pasajero no disponible'; end if;
  if exists(select 1 from public.trips where passenger_id=auth.uid() and status in ('solicitado','aceptado','chofer_en_camino','chofer_llego','en_viaje')) then raise exception 'Ya tienes un viaje activo'; end if;
  select * into fare_row from public.fares where active=true order by created_at desc limit 1;
  d := public.civimoto_distance_km(p_origin_lat,p_origin_lng,p_destination_lat,p_destination_lng);
  f := greatest(coalesce(fare_row.minimum_fare,5), coalesce(fare_row.base_fare,3) + d*coalesce(fare_row.per_km,1.5));
  insert into public.trips(passenger_id,origin_address,origin_lat,origin_lng,destination_address,destination_lat,destination_lng,estimated_distance_km,estimated_fare,payment_method)
  values(auth.uid(),coalesce(nullif(trim(p_origin_address),''),'Mi ubicación'),p_origin_lat,p_origin_lng,coalesce(nullif(trim(p_destination_address),''),'Destino'),p_destination_lat,p_destination_lng,d,round(f,2),case when lower(p_payment_method)='yape' then 'yape' else 'efectivo' end)
  returning * into out_trip;
  return out_trip;
end;
$$;

grant execute on function public.request_civimoto_trip(text,double precision,double precision,text,double precision,double precision,text) to authenticated;

create or replace function public.accept_civimoto_trip(p_trip_id uuid)
returns public.trips
language plpgsql
security invoker
set search_path=public
as $$
declare out_trip public.trips%rowtype;
begin
  if not exists(select 1 from public.drivers where id=auth.uid() and status='aprobado' and is_available=true) then raise exception 'Chofer no disponible o no aprobado'; end if;
  update public.trips set driver_id=auth.uid(),status='aceptado',accepted_at=now()
  where id=p_trip_id and status='solicitado' and driver_id is null
  returning * into out_trip;
  if out_trip.id is null then raise exception 'El servicio ya fue tomado'; end if;
  return out_trip;
end;
$$;
grant execute on function public.accept_civimoto_trip(uuid) to authenticated;

create or replace function public.driver_set_live_location(p_lat double precision,p_lng double precision,p_heading double precision default null,p_speed_kmh double precision default null)
returns public.driver_live_locations
language plpgsql
security invoker
set search_path=public
as $$
declare out_row public.driver_live_locations%rowtype;
begin
  if not exists(select 1 from public.drivers where id=auth.uid()) then raise exception 'Solo chofer'; end if;
  insert into public.driver_live_locations(driver_id,lat,lng,heading,speed_kmh,updated_at)
  values(auth.uid(),p_lat,p_lng,p_heading,p_speed_kmh,now())
  on conflict(driver_id) do update set lat=excluded.lat,lng=excluded.lng,heading=excluded.heading,speed_kmh=excluded.speed_kmh,updated_at=now()
  returning * into out_row;
  return out_row;
end;
$$;
grant execute on function public.driver_set_live_location(double precision,double precision,double precision,double precision) to authenticated;

create or replace function public.driver_update_civimoto_trip(p_trip_id uuid,p_status public.trip_status)
returns public.trips
language plpgsql
security invoker
set search_path=public
as $$
declare t public.trips%rowtype;
begin
  select * into t from public.trips where id=p_trip_id and driver_id=auth.uid() for update;
  if t.id is null then raise exception 'Viaje no encontrado'; end if;
  if p_status='chofer_en_camino' and t.status='aceptado' then null;
  elsif p_status='chofer_llego' and t.status='chofer_en_camino' then null;
  elsif p_status='en_viaje' and t.status in ('chofer_llego','aceptado') then null;
  elsif p_status='completado' and t.status='en_viaje' then null;
  elsif p_status='cancelado' and t.status in ('aceptado','chofer_en_camino','chofer_llego') then null;
  else raise exception 'Transición de estado inválida'; end if;
  update public.trips set status=p_status,
    started_at=case when p_status='en_viaje' then coalesce(started_at,now()) else started_at end,
    completed_at=case when p_status='completado' then now() else completed_at end,
    final_fare=case when p_status='completado' then coalesce(final_fare,estimated_fare) else final_fare end
  where id=p_trip_id returning * into t;
  return t;
end;
$$;
grant execute on function public.driver_update_civimoto_trip(uuid,public.trip_status) to authenticated;

create or replace function public.passenger_cancel_civimoto_trip(p_trip_id uuid,p_reason text default 'Cancelado por pasajero')
returns public.trips
language plpgsql
security invoker
set search_path=public
as $$
declare t public.trips%rowtype;
begin
  update public.trips set status='cancelado',cancellation_reason=left(coalesce(p_reason,'Cancelado por pasajero'),300)
  where id=p_trip_id and passenger_id=auth.uid() and status in ('solicitado','aceptado','chofer_en_camino','chofer_llego')
  returning * into t;
  if t.id is null then raise exception 'El viaje ya no puede cancelarse'; end if;
  return t;
end;
$$;
grant execute on function public.passenger_cancel_civimoto_trip(uuid,text) to authenticated;

alter table public.profiles enable row level security;
alter table public.drivers enable row level security;
alter table public.vehicles enable row level security;
alter table public.fares enable row level security;
alter table public.trips enable row level security;
alter table public.driver_live_locations enable row level security;
alter table public.trip_locations enable row level security;
alter table public.driver_subscription_payments enable row level security;
alter table public.driver_billing enable row level security;
alter table public.passenger_notifications enable row level security;
alter table public.driver_notifications enable row level security;

create policy profiles_self_admin_read on public.profiles for select to authenticated using (id=auth.uid() or private.is_admin());
create policy profiles_self_admin_update on public.profiles for update to authenticated using (id=auth.uid() or private.is_admin()) with check (id=auth.uid() or private.is_admin());

create policy drivers_read on public.drivers for select to authenticated using (id=auth.uid() or status='aprobado' or private.is_admin());
create policy drivers_self_update on public.drivers for update to authenticated using (id=auth.uid() or private.is_admin()) with check (id=auth.uid() or private.is_admin());

create policy vehicles_read on public.vehicles for select to authenticated using (driver_id=auth.uid() or active=true or private.is_admin());
create policy vehicles_owner_admin_write on public.vehicles for all to authenticated using (driver_id=auth.uid() or private.is_admin()) with check (driver_id=auth.uid() or private.is_admin());

create policy fares_read on public.fares for select to authenticated using (active=true or private.is_admin());
create policy fares_admin_write on public.fares for all to authenticated using (private.is_admin()) with check (private.is_admin());

create policy trips_create_passenger on public.trips for insert to authenticated with check (passenger_id=auth.uid());
create policy trips_read_participants_admin on public.trips for select to authenticated using (
  passenger_id=auth.uid() or driver_id=auth.uid() or private.is_admin() or
  (status='solicitado' and exists(select 1 from public.drivers d where d.id=auth.uid() and d.status='aprobado' and d.is_available=true))
);
create policy trips_update_participants_admin on public.trips for update to authenticated using (passenger_id=auth.uid() or driver_id=auth.uid() or private.is_admin());

create policy live_locations_read on public.driver_live_locations for select to authenticated using (
  driver_id=auth.uid() or private.is_admin() or exists(select 1 from public.trips t where t.driver_id=driver_live_locations.driver_id and t.passenger_id=auth.uid() and t.status in ('aceptado','chofer_en_camino','chofer_llego','en_viaje'))
);
create policy live_locations_driver_write on public.driver_live_locations for all to authenticated using (driver_id=auth.uid()) with check (driver_id=auth.uid());

create policy trip_locations_read on public.trip_locations for select to authenticated using (exists(select 1 from public.trips t where t.id=trip_id and (t.passenger_id=auth.uid() or t.driver_id=auth.uid() or private.is_admin())));
create policy trip_locations_insert on public.trip_locations for insert to authenticated with check (actor_id=auth.uid() and exists(select 1 from public.trips t where t.id=trip_id and (t.passenger_id=auth.uid() or t.driver_id=auth.uid())));

create policy subscription_driver_admin_read on public.driver_subscription_payments for select to authenticated using (driver_id=auth.uid() or private.is_admin());
create policy subscription_driver_insert on public.driver_subscription_payments for insert to authenticated with check (driver_id=auth.uid() and status='pendiente');
create policy subscription_admin_update on public.driver_subscription_payments for update to authenticated using (private.is_admin()) with check (private.is_admin());

create policy billing_read on public.driver_billing for select to authenticated using (true);
create policy billing_admin_write on public.driver_billing for all to authenticated using (private.is_admin()) with check (private.is_admin());

create policy passenger_notifications_read on public.passenger_notifications for select to authenticated using (passenger_id=auth.uid() or private.is_admin());
create policy passenger_notifications_update on public.passenger_notifications for update to authenticated using (passenger_id=auth.uid() or private.is_admin());
create policy driver_notifications_read on public.driver_notifications for select to authenticated using (driver_id=auth.uid() or private.is_admin());
create policy driver_notifications_update on public.driver_notifications for update to authenticated using (driver_id=auth.uid() or private.is_admin());

-- Realtime solo para CiviMoto.
do $$ begin
  alter publication supabase_realtime add table public.trips;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.driver_live_locations;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.driver_subscription_payments;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.passenger_notifications;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.driver_notifications;
exception when duplicate_object then null; end $$;
