package pe.civimoto.administrador;

import android.app.Activity;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.Gravity;
import android.view.View;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.*;
import org.json.JSONArray;
import org.json.JSONObject;

public class FlowActivity extends Activity implements RealtimeBridge.Listener {
    private final int GOLD=Color.rgb(255,190,0),GOLD2=Color.rgb(255,220,90),BLACK=Color.rgb(5,6,8),PANEL=Color.rgb(18,20,24),PANEL2=Color.rgb(29,31,37),MUTED=Color.rgb(176,180,190),RED=Color.rgb(235,65,65),GREEN=Color.rgb(35,190,105),BLUE=Color.rgb(40,126,230),PURPLE=Color.rgb(132,67,230);
    private final Handler h=new Handler(Looper.getMainLooper()); private Backend backend; private RealtimeBridge realtime; private Runnable poller; private LinearLayout body; private TextView connection; private WebView map;

    int dp(int v){return(int)(v*getResources().getDisplayMetrics().density);} GradientDrawable shape(int c,int r,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));if(stroke>0)g.setStroke(dp(stroke),GOLD);return g;} GradientDrawable gold(){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{GOLD2,GOLD,Color.rgb(255,158,0)});g.setCornerRadius(dp(16));return g;}
    TextView tx(String s,int sp,int c,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(c);if(b)t.setTypeface(null,1);t.setPadding(0,dp(3),0,dp(3));return t;} ImageView logo(int s){ImageView i=new ImageView(this);i.setImageResource(R.drawable.logo_civimoto);i.setScaleType(ImageView.ScaleType.CENTER_CROP);i.setBackground(shape(Color.BLACK,22,1));i.setClipToOutline(true);i.setLayoutParams(new LinearLayout.LayoutParams(dp(s),dp(s)));return i;}
    LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(15),dp(16),dp(15));c.setBackground(shape(PANEL,20,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(7),0,dp(7));c.setLayoutParams(lp);return c;} LinearLayout subCard(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(12),dp(10),dp(12),dp(10));c.setBackground(shape(PANEL2,14,0));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(4),0,dp(4));c.setLayoutParams(lp);return c;}
    EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setHintTextColor(MUTED);e.setTextColor(Color.WHITE);e.setSingleLine(true);e.setPadding(dp(14),dp(11),dp(14),dp(11));e.setBackground(shape(PANEL2,14,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(54));lp.setMargins(0,dp(5),0,dp(5));e.setLayoutParams(lp);return e;} Button btn(String s,boolean p){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(15);b.setTypeface(null,1);b.setTextColor(p?Color.BLACK:Color.WHITE);b.setBackground(p?gold():shape(PANEL2,16,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(52));lp.setMargins(0,dp(5),0,dp(5));b.setLayoutParams(lp);return b;} Button action(String s,int c){Button b=btn(s,false);b.setBackground(shape(c,14,0));return b;}

    @Override public void onCreate(Bundle b){super.onCreate(b);backend=new Backend(this);showSplash();h.postDelayed(()->backend.bootstrap(new Backend.Callback(){public void ok(Object v){if(backend.hasSession())backend.resume("admin",new Backend.Callback(){public void ok(Object x){screenDashboard();}public void error(String m){screenLogin();}});else screenLogin();}public void error(String m){screenLogin();toast("Servidor: "+m);}}),900);}
    void showSplash(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setGravity(Gravity.CENTER);r.setPadding(dp(28),dp(28),dp(28),dp(28));r.setBackgroundColor(BLACK);r.addView(logo(260));TextView n=tx("CiviMoto",48,Color.WHITE,true);n.setGravity(Gravity.CENTER);r.addView(n);TextView t=tx("Administrador · Control total",19,GOLD2,true);t.setGravity(Gravity.CENTER);r.addView(t);setContentView(r);}
    void shell(String title,String subtitle,int step){stopPoller();ScrollView sc=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(14),dp(14),dp(14),dp(70));root.setBackgroundColor(BLACK);sc.addView(root);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.addView(logo(62));LinearLayout ht=new LinearLayout(this);ht.setOrientation(LinearLayout.VERTICAL);ht.setPadding(dp(11),0,0,0);ht.addView(tx(title,25,Color.WHITE,true));ht.addView(tx(subtitle,12,GOLD2,false));head.addView(ht,new LinearLayout.LayoutParams(0,-2,1));TextView badge=tx(step+" / 6",12,GOLD2,true);badge.setPadding(dp(10),dp(7),dp(10),dp(7));badge.setBackground(shape(PANEL2,18,1));head.addView(badge);root.addView(head);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(0,dp(12),0,0);root.addView(body);setContentView(sc);}

    void screenLogin(){shell("CiviMoto Admin","Pantalla 1 · Iniciar sesión",1);LinearLayout c=card();c.addView(tx("Acceso administrador",23,Color.WHITE,true));EditText email=input("Correo administrador"),pass=input("Contraseña");pass.setInputType(0x81);c.addView(email);c.addView(pass);Button login=btn("Ingresar al panel",true),setup=btn("Configurar primer administrador",false);c.addView(login);c.addView(setup);body.addView(c);login.setOnClickListener(v->{login.setEnabled(false);backend.login(email.getText().toString(),pass.getText().toString(),"admin",new Backend.Callback(){public void ok(Object x){screenDashboard();}public void error(String m){login.setEnabled(true);toast(m);}});});setup.setOnClickListener(v->screenRegisterAdmin());}
    void screenRegisterAdmin(){shell("Administrador inicial","Pantalla 2 · Registro / configuración",2);LinearLayout c=card();c.addView(tx("Crear o activar administrador CiviMoto",22,Color.WHITE,true));c.addView(tx("Usa un correo nuevo y una contraseña de 8 o más caracteres. Si el administrador ya existe, esta pantalla también sirve para iniciar sesión.",13,MUTED,false));EditText email=input("Correo administrador"),pass=input("Contraseña 8+ caracteres");pass.setInputType(0x81);c.addView(email);c.addView(pass);Button create=btn("Crear / activar administrador",true),back=btn("Volver",false);c.addView(create);c.addView(back);body.addView(c);create.setOnClickListener(v->{create.setEnabled(false);backend.login(email.getText().toString(),pass.getText().toString(),"admin",new Backend.Callback(){public void ok(Object x){screenDashboard();}public void error(String m){create.setEnabled(true);toast(m);}});});back.setOnClickListener(v->screenLogin());}

    void screenDashboard(){shell("Dashboard","Pantalla 3 · Resumen general",3);connection=tx("Conectando en tiempo real…",12,MUTED,false);body.addView(connection);LinearLayout row1=new LinearLayout(this),row2=new LinearLayout(this);TextView users=metric("—","Usuarios",BLUE),drivers=metric("—","Choferes",Color.rgb(215,160,0)),trips=metric("—","Viajes",GREEN),gross=metric("—","Facturado",PURPLE);row1.addView(users,new LinearLayout.LayoutParams(0,dp(92),1));row1.addView(drivers,new LinearLayout.LayoutParams(0,dp(92),1));row2.addView(trips,new LinearLayout.LayoutParams(0,dp(92),1));row2.addView(gross,new LinearLayout.LayoutParams(0,dp(92),1));body.addView(row1);body.addView(row2);LinearLayout nav=card();Button drv=btn("Gestión de choferes",false),live=btn("Viajes en tiempo real",true),pay=btn("Pagos y configuración",false),logout=btn("Cerrar sesión",false);nav.addView(drv);nav.addView(live);nav.addView(pay);nav.addView(logout);body.addView(nav);drv.setOnClickListener(v->screenDrivers());live.setOnClickListener(v->screenTrips());pay.setOnClickListener(v->screenPayments());logout.setOnClickListener(v->{backend.logout();stopAll();screenLogin();});loadMetrics(users,drivers,trips,gross);startRealtime();startPoller(()->loadMetrics(users,drivers,trips,gross));}
    TextView metric(String value,String label,int color){TextView t=tx(value+"\n"+label,18,Color.WHITE,true);t.setGravity(Gravity.CENTER);t.setPadding(dp(8),dp(12),dp(8),dp(12));t.setBackground(shape(color,18,0));return t;}
    void loadMetrics(TextView users,TextView drivers,TextView trips,TextView gross){backend.rest("GET","profiles?select=id,role",null,new Backend.Callback(){public void ok(Object x){if(x instanceof JSONArray){JSONArray a=(JSONArray)x;int n=0;for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null&&"usuario".equals(o.optString("role")))n++;}users.setText(n+"\nUsuarios");}}public void error(String m){}});backend.rest("GET","drivers?select=id,is_available",null,new Backend.Callback(){public void ok(Object x){if(x instanceof JSONArray){JSONArray a=(JSONArray)x;int on=0;for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null&&o.optBoolean("is_available"))on++;}drivers.setText(a.length()+"\nChoferes · "+on+" online");}}public void error(String m){}});backend.rest("GET","trips?order=requested_at.desc&limit=500&select=id,status,estimated_fare,final_fare",null,new Backend.Callback(){public void ok(Object x){if(x instanceof JSONArray){JSONArray a=(JSONArray)x;double total=0;int done=0;for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null&&"completado".equals(o.optString("status"))){done++;total+=o.optDouble("final_fare",o.optDouble("estimated_fare",0));}}trips.setText(a.length()+"\nViajes · "+done+" completados");gross.setText("S/ "+String.format("%.2f",total)+"\nFacturado");}}public void error(String m){}});}

    void screenDrivers(){shell("Gestión de choferes","Pantalla 4 · Aprobar, rechazar y controlar",4);LinearLayout box=card();box.addView(tx("Choferes pendientes",22,Color.WHITE,true));body.addView(box);Button back=btn("Volver al dashboard",false);body.addView(back);back.setOnClickListener(v->screenDashboard());loadDrivers(box);startRealtime();}
    void loadDrivers(LinearLayout box){while(box.getChildCount()>1)box.removeViewAt(1);backend.rpc("admin_driver_directory",new JSONObject(),new Backend.Callback(){public void ok(Object x){if(!(x instanceof JSONArray)){box.addView(tx("Sin datos.",14,MUTED,false));return;}JSONArray a=(JSONArray)x;int pending=0;for(int i=0;i<a.length();i++){JSONObject d=a.optJSONObject(i);if(d==null||!"pendiente".equals(d.optString("status")))continue;pending++;LinearLayout c=subCard();c.addView(tx(d.optString("full_name","Chofer")+" · "+d.optString("plate","Sin placa"),15,Color.WHITE,true));c.addView(tx("DNI: "+d.optString("document_number","—")+" · Licencia: "+d.optString("license_number","—"),12,MUTED,false));LinearLayout r=new LinearLayout(FlowActivity.this);Button no=action("Rechazar",RED),yes=action("Aprobar",GREEN);r.addView(no,new LinearLayout.LayoutParams(0,dp(48),1));r.addView(yes,new LinearLayout.LayoutParams(0,dp(48),1));c.addView(r);box.addView(c);String id=d.optString("id");yes.setOnClickListener(v->reviewDriver(id,"aprobado",box));no.setOnClickListener(v->reviewDriver(id,"rechazado",box));}if(pending==0)box.addView(tx("No hay choferes pendientes.",14,MUTED,false));}public void error(String m){box.addView(tx("Error: "+m,14,RED,false));}});}
    void reviewDriver(String id,String status,LinearLayout box){try{backend.rpc("admin_set_driver_status",new JSONObject().put("p_driver_id",id).put("p_status",status),new Backend.Callback(){public void ok(Object x){toast("Chofer "+status);loadDrivers(box);}public void error(String m){toast(m);}});}catch(Exception ignored){}}

    void screenTrips(){shell("Viajes en tiempo real","Pantalla 5 · Operación en vivo",5);connection=tx("Sincronizando viajes y GPS…",12,MUTED,false);body.addView(connection);map=createMap();body.addView(map,new LinearLayout.LayoutParams(-1,dp(320)));LinearLayout listCard=card();listCard.addView(tx("Viajes recientes",21,Color.WHITE,true));TextView list=tx("Cargando…",14,MUTED,false);listCard.addView(list);body.addView(listCard);Button back=btn("Volver al dashboard",false);body.addView(back);back.setOnClickListener(v->screenDashboard());loadTrips(list);loadMap();startRealtime();startPoller(()->{loadTrips(list);loadMap();});}
    void loadTrips(TextView list){backend.rest("GET","trips?order=requested_at.desc&limit=15&select=id,status,origin_address,destination_address,estimated_fare,final_fare",null,new Backend.Callback(){public void ok(Object x){if(!(x instanceof JSONArray)){list.setText("Sin viajes.");return;}JSONArray a=(JSONArray)x;StringBuilder s=new StringBuilder();for(int i=0;i<a.length();i++){JSONObject t=a.optJSONObject(i);if(t!=null)s.append("• ").append(t.optString("status","—")).append(" · ").append(t.optString("origin_address","Origen")).append(" → ").append(t.optString("destination_address","Destino")).append(" · S/ ").append(t.optString("final_fare",t.optString("estimated_fare","—"))).append("\n");}list.setText(s.length()==0?"Sin viajes.":s.toString().trim());}public void error(String m){list.setText("No se pudo cargar viajes.");}});}

    void screenPayments(){shell("Pagos y configuración","Pantalla 6 · Yape, membresía y tarifas",6);LinearLayout pay=card();pay.addView(tx("Pagos de choferes pendientes",21,Color.WHITE,true));LinearLayout payments=new LinearLayout(this);payments.setOrientation(LinearLayout.VERTICAL);pay.addView(payments);body.addView(pay);LinearLayout cfg=card();cfg.addView(tx("Membresía y Yape",20,Color.WHITE,true));EditText weekly=input("Monto semanal"),monthly=input("Monto mensual"),yapeName=input("Nombre en Yape"),yapeNumber=input("Número Yape");cfg.addView(weekly);cfg.addView(monthly);cfg.addView(yapeName);cfg.addView(yapeNumber);Button saveCfg=btn("Guardar configuración Yape",true);cfg.addView(saveCfg);body.addView(cfg);LinearLayout fare=card();fare.addView(tx("Tarifas CiviMoto",20,Color.WHITE,true));fare.addView(tx("Comisión porcentual: 0%. Solo membresía semanal o mensual.",13,GOLD2,true));EditText base=input("Tarifa base"),km=input("Precio por km"),min=input("Tarifa mínima");fare.addView(base);fare.addView(km);fare.addView(min);Button saveFare=btn("Guardar tarifas",true),back=btn("Volver al dashboard",false);fare.addView(saveFare);fare.addView(back);body.addView(fare);back.setOnClickListener(v->screenDashboard());saveCfg.setOnClickListener(v->saveBilling(weekly,monthly,yapeName,yapeNumber));saveFare.setOnClickListener(v->saveFare(base,km,min));loadPayments(payments);loadBilling(weekly,monthly,yapeName,yapeNumber);loadFares(base,km,min);startRealtime();}
    void loadPayments(LinearLayout box){box.removeAllViews();backend.rest("GET","driver_subscription_payments?status=eq.pending&order=submitted_at.asc&limit=40&select=*",null,new Backend.Callback(){public void ok(Object x){if(!(x instanceof JSONArray)){box.addView(tx("Sin pagos pendientes.",14,MUTED,false));return;}JSONArray a=(JSONArray)x;if(a.length()==0){box.addView(tx("No hay pagos pendientes.",14,MUTED,false));return;}for(int i=0;i<a.length();i++){JSONObject p=a.optJSONObject(i);if(p==null)continue;LinearLayout c=subCard();c.addView(tx(p.optString("plan","weekly").toUpperCase()+" · S/ "+p.optString("amount","0"),15,Color.WHITE,true));c.addView(tx("Operación Yape: "+p.optString("yape_operation","—"),12,MUTED,false));LinearLayout r=new LinearLayout(FlowActivity.this);Button no=action("Rechazar",RED),yes=action("Aprobar",GREEN);r.addView(no,new LinearLayout.LayoutParams(0,dp(48),1));r.addView(yes,new LinearLayout.LayoutParams(0,dp(48),1));c.addView(r);box.addView(c);String id=p.optString("id");yes.setOnClickListener(v->reviewPayment(id,true,box));no.setOnClickListener(v->reviewPayment(id,false,box));}}public void error(String m){box.addView(tx("Error: "+m,14,RED,false));}});}
    void reviewPayment(String id,boolean approve,LinearLayout box){try{backend.rpc("admin_review_driver_membership_payment",new JSONObject().put("p_payment_id",id).put("p_approve",approve).put("p_note","Revisado desde CiviMoto Admin"),new Backend.Callback(){public void ok(Object x){toast(approve?"Pago aprobado":"Pago rechazado");loadPayments(box);}public void error(String m){toast(m);}});}catch(Exception ignored){}}
    void loadBilling(EditText weekly,EditText monthly,EditText name,EditText number){backend.rest("GET","driver_billing_config?id=eq.true&select=*",null,new Backend.Callback(){public void ok(Object x){JSONObject c=Backend.firstObject(x);if(c!=null){weekly.setText(c.optString("weekly_amount","0"));monthly.setText(c.optString("monthly_amount","0"));name.setText(c.optString("yape_display_name",""));number.setText(c.optString("yape_number",""));}}public void error(String m){}});}
    void saveBilling(EditText weekly,EditText monthly,EditText name,EditText number){try{JSONObject b=new JSONObject().put("weekly_amount",Double.parseDouble(weekly.getText().toString())).put("monthly_amount",Double.parseDouble(monthly.getText().toString())).put("yape_display_name",name.getText().toString().trim()).put("yape_number",number.getText().toString().trim());backend.rest("PATCH","driver_billing_config?id=eq.true",b,new Backend.Callback(){public void ok(Object x){toast("Configuración Yape guardada");}public void error(String m){toast(m);}});}catch(Exception e){toast("Revisa los montos");}}
    void loadFares(EditText base,EditText km,EditText min){backend.rest("GET","fares?active=eq.true&order=created_at.desc&limit=1&select=id,base_fare,per_km,minimum_fare",null,new Backend.Callback(){public void ok(Object x){JSONObject f=Backend.firstObject(x);if(f!=null){base.setText(f.optString("base_fare","3.00"));km.setText(f.optString("per_km","1.50"));min.setText(f.optString("minimum_fare","5.00"));}}public void error(String m){}});}
    void saveFare(EditText base,EditText km,EditText min){try{JSONObject b=new JSONObject().put("base_fare",Double.parseDouble(base.getText().toString())).put("per_km",Double.parseDouble(km.getText().toString())).put("minimum_fare",Double.parseDouble(min.getText().toString())).put("platform_commission_percent",0);backend.rest("PATCH","fares?active=eq.true",b,new Backend.Callback(){public void ok(Object x){toast("Tarifas actualizadas");}public void error(String m){toast(m);}});}catch(Exception e){toast("Revisa las tarifas");}}

    void loadMap(){backend.rest("GET","driver_live_locations?select=driver_id,lat,lng,updated_at",null,new Backend.Callback(){public void ok(Object x){if(x instanceof JSONArray&&map!=null)map.evaluateJavascript("setDrivers("+JSONObject.quote(x.toString())+")",null);}public void error(String m){}});}
    WebView createMap(){WebView w=new WebView(this);WebSettings s=w.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);w.setWebViewClient(new WebViewClient());String html="<!doctype html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'><link href='https://unpkg.com/maplibre-gl@5.6.2/dist/maplibre-gl.css' rel='stylesheet'><style>html,body,#m{margin:0;width:100%;height:100%;background:#101216}</style></head><body><div id='m'></div><script src='https://unpkg.com/maplibre-gl@5.6.2/dist/maplibre-gl.js'></script><script>let map=new maplibregl.Map({container:'m',style:'https://tiles.openfreemap.org/styles/liberty',center:[-77.0428,-12.0464],zoom:12.5});let marks=[];function setDrivers(s){marks.forEach(x=>x.remove());marks=[];try{JSON.parse(s).forEach(d=>marks.push(new maplibregl.Marker({color:'#ffbe00'}).setLngLat([d.lng,d.lat]).addTo(map)));}catch(e){}}</script></body></html>";w.loadDataWithBaseURL("https://admin.civimoto.local/",html,"text/html","UTF-8",null);return w;}
    void startRealtime(){stopRealtime();realtime=new RealtimeBridge(this,backend,this);WebView w=realtime.start("cm_trips","cm_driver_live_locations","cm_driver_subscription_payments","cm_drivers","cm_profiles");w.setVisibility(View.INVISIBLE);body.addView(w,new LinearLayout.LayoutParams(1,1));}
    void startPoller(Runnable work){stopPoller();poller=new Runnable(){public void run(){if(backend.hasSession())work.run();h.postDelayed(this,6000);}};h.postDelayed(poller,6000);} void stopPoller(){if(poller!=null){h.removeCallbacks(poller);poller=null;}} void stopRealtime(){if(realtime!=null){realtime.stop();realtime=null;}} public void onRealtime(String table,String payload){if(connection!=null)connection.setText("● En tiempo real");} public void onRealtimeStatus(String s){if(connection!=null)connection.setText("SUBSCRIBED".equals(s)?"● En tiempo real":"Sincronizando…");}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();} void stopAll(){stopRealtime();stopPoller();} @Override protected void onDestroy(){super.onDestroy();stopAll();}
}
