package pe.civimoto.administrador;

import android.app.Activity;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.Gravity;
import android.view.View;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.*;
import org.json.JSONArray;
import org.json.JSONObject;

public class PremiumActivity extends Activity implements RealtimeBridge.Listener {
    private final int GOLD=Color.rgb(255,190,0), GOLD2=Color.rgb(255,215,70), BLACK=Color.rgb(7,8,10), PANEL=Color.rgb(18,20,24), PANEL2=Color.rgb(27,29,34), MUTED=Color.rgb(170,174,184), GREEN=Color.rgb(38,190,105), RED=Color.rgb(235,64,64), BLUE=Color.rgb(38,126,230), PURPLE=Color.rgb(130,67,230);
    private final Handler handler=new Handler(Looper.getMainLooper());
    private Backend backend; private RealtimeBridge realtime; private LinearLayout root,driversBox,paymentsBox; private WebView map;
    private TextView connection,usersMetric,driversMetric,tripsMetric,revenueMetric; private EditText weekly,monthly,yapeName,yapeNumber,baseFare,perKm,minFare; private Runnable poller;

    int dp(int v){return (int)(v*getResources().getDisplayMetrics().density);}
    GradientDrawable shape(int c,int r,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));if(stroke>0)g.setStroke(dp(stroke),GOLD);return g;}
    GradientDrawable gold(){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{GOLD2,GOLD,Color.rgb(255,155,0)});g.setCornerRadius(dp(16));return g;}
    TextView txt(String s,int sp,int c,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(c);if(b)t.setTypeface(null,1);t.setPadding(0,dp(3),0,dp(3));return t;}
    ImageView logo(int s){ImageView i=new ImageView(this);i.setImageResource(R.drawable.logo_civimoto);i.setScaleType(ImageView.ScaleType.CENTER_CROP);i.setBackground(shape(Color.BLACK,22,1));i.setClipToOutline(true);i.setLayoutParams(new LinearLayout.LayoutParams(dp(s),dp(s)));return i;}
    LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(15),dp(16),dp(15));c.setBackground(shape(PANEL,20,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(7),0,dp(7));c.setLayoutParams(lp);return c;}
    Button primary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.BLACK);b.setTypeface(null,1);b.setTextSize(15);b.setBackground(gold());LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(52));lp.setMargins(0,dp(5),0,dp(5));b.setLayoutParams(lp);return b;}
    Button dark(String s){Button b=primary(s);b.setTextColor(Color.WHITE);b.setBackground(shape(PANEL2,16,1));return b;}
    Button action(String s,int c){Button b=primary(s);b.setTextColor(Color.WHITE);b.setBackground(shape(c,14,0));return b;}
    EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setHintTextColor(MUTED);e.setTextColor(Color.WHITE);e.setSingleLine(true);e.setPadding(dp(14),dp(12),dp(14),dp(12));e.setBackground(shape(PANEL2,14,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(54));lp.setMargins(0,dp(5),0,dp(5));e.setLayoutParams(lp);return e;}
    TextView metric(String value,String label,int c){TextView t=txt(value+"\n"+label,18,Color.WHITE,true);t.setGravity(Gravity.CENTER);t.setPadding(dp(8),dp(13),dp(8),dp(13));t.setBackground(shape(c,18,0));return t;}
    TextView chip(String s){TextView t=txt(s,12,GOLD2,true);t.setGravity(Gravity.CENTER);t.setPadding(dp(12),dp(8),dp(12),dp(8));t.setBackground(shape(PANEL2,20,1));return t;}

    @Override public void onCreate(Bundle b){super.onCreate(b);backend=new Backend(this);showSplash();handler.postDelayed(()->backend.bootstrap(new Backend.Callback(){public void ok(Object v){if(backend.hasSession())backend.resume("admin",new Backend.Callback(){public void ok(Object x){showDashboard();}public void error(String m){showLogin();}});else showLogin();}public void error(String m){showLogin();toast("Servidor: "+m);}}),900);}
    void showSplash(){LinearLayout s=new LinearLayout(this);s.setOrientation(LinearLayout.VERTICAL);s.setGravity(Gravity.CENTER);s.setPadding(dp(28),dp(30),dp(28),dp(30));s.setBackgroundColor(BLACK);s.addView(logo(250));TextView n=txt("CiviMoto",48,Color.WHITE,true);n.setGravity(Gravity.CENTER);s.addView(n);TextView tag=txt("Administrador · Control total en tus manos",18,GOLD2,true);tag.setGravity(Gravity.CENTER);s.addView(tag);TextView p=chip("GESTIONA  •  CONTROLA  •  HAZ CRECER");LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2);lp.setMargins(0,dp(22),0,0);p.setLayoutParams(lp);s.addView(p);setContentView(s);}

    void showLogin(){ScrollView sc=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(22),dp(24),dp(22),dp(38));r.setBackgroundColor(BLACK);sc.addView(r);setContentView(sc);LinearLayout brand=new LinearLayout(this);brand.setOrientation(LinearLayout.VERTICAL);brand.setGravity(Gravity.CENTER);brand.addView(logo(145));TextView title=txt("CiviMoto",38,Color.WHITE,true);title.setGravity(Gravity.CENTER);brand.addView(title);TextView sub=txt("Acceso Administrador",16,GOLD2,true);sub.setGravity(Gravity.CENTER);brand.addView(sub);r.addView(brand);LinearLayout c=card();c.addView(txt("Panel de administración",21,Color.WHITE,true));c.addView(txt("En el primer acceso, un correo nuevo con contraseña de 8+ caracteres crea el administrador inicial de CiviMoto.",12,MUTED,false));EditText email=input("Correo administrador");EditText pass=input("Contraseña");pass.setInputType(0x81);c.addView(email);c.addView(pass);Button login=primary("Ingresar al panel");c.addView(login);r.addView(c);LinearLayout f=card();f.addView(txt("Operación en tiempo real",18,Color.WHITE,true));f.addView(txt("• Choferes y pasajeros exclusivos de CiviMoto\n• Viajes en vivo\n• Pagos semanales y mensuales\n• Tarifas y Yape configurables",14,MUTED,false));r.addView(f);login.setOnClickListener(v->{login.setEnabled(false);backend.login(email.getText().toString(),pass.getText().toString(),"admin",new Backend.Callback(){public void ok(Object x){showDashboard();}public void error(String m){login.setEnabled(true);toast(m);}});});}

    void showDashboard(){ScrollView sc=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(14),dp(14),dp(14),dp(90));root.setBackgroundColor(BLACK);sc.addView(root);setContentView(sc);LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.addView(logo(60));LinearLayout ht=new LinearLayout(this);ht.setOrientation(LinearLayout.VERTICAL);ht.setPadding(dp(11),0,0,0);ht.addView(txt("CiviMoto Admin",26,Color.WHITE,true));connection=txt("Conectando en tiempo real…",12,MUTED,false);ht.addView(connection);h.addView(ht,new LinearLayout.LayoutParams(0,-2,1));Button out=dark("Salir");out.setLayoutParams(new LinearLayout.LayoutParams(dp(82),dp(48)));h.addView(out);root.addView(h);out.setOnClickListener(v->{backend.logout();stopRealtime();showLogin();});
        TextView title=txt("Dashboard",27,Color.WHITE,true);title.setPadding(0,dp(12),0,dp(6));root.addView(title);LinearLayout m1=new LinearLayout(this);usersMetric=metric("—","Usuarios",BLUE);driversMetric=metric("—","Choferes",Color.rgb(218,160,0));m1.addView(usersMetric,new LinearLayout.LayoutParams(0,dp(90),1));m1.addView(driversMetric,new LinearLayout.LayoutParams(0,dp(90),1));root.addView(m1);LinearLayout m2=new LinearLayout(this);tripsMetric=metric("—","Viajes hoy",GREEN);revenueMetric=metric("—","Facturado",PURPLE);m2.addView(tripsMetric,new LinearLayout.LayoutParams(0,dp(90),1));m2.addView(revenueMetric,new LinearLayout.LayoutParams(0,dp(90),1));root.addView(m2);
        LinearLayout live=card();live.addView(txt("Viajes y choferes en tiempo real",20,Color.WHITE,true));map=createMap();live.addView(map,new LinearLayout.LayoutParams(-1,dp(310)));root.addView(live);
        LinearLayout drv=card();drv.addView(txt("Gestión de choferes",20,Color.WHITE,true));drv.addView(txt("Aprueba o rechaza nuevas cuentas CiviMoto",13,MUTED,false));driversBox=new LinearLayout(this);driversBox.setOrientation(LinearLayout.VERTICAL);drv.addView(driversBox);root.addView(drv);
        LinearLayout pay=card();pay.addView(txt("Pagos de choferes",20,Color.WHITE,true));pay.addView(txt("Membresía semanal / mensual · Yape",13,MUTED,false));paymentsBox=new LinearLayout(this);paymentsBox.setOrientation(LinearLayout.VERTICAL);pay.addView(paymentsBox);root.addView(pay);
        LinearLayout config=card();config.addView(txt("Configuración de membresía",20,Color.WHITE,true));weekly=input("Monto semanal");monthly=input("Monto mensual");yapeName=input("Nombre en Yape");yapeNumber=input("Número Yape");config.addView(weekly);config.addView(monthly);config.addView(yapeName);config.addView(yapeNumber);Button savePay=primary("Guardar configuración Yape");config.addView(savePay);root.addView(config);
        LinearLayout fares=card();fares.addView(txt("Tarifas CiviMoto",20,Color.WHITE,true));fares.addView(txt("Sin comisión porcentual. Solo membresía semanal o mensual.",13,GOLD2,true));baseFare=input("Tarifa base");perKm=input("Precio por km");minFare=input("Tarifa mínima");fares.addView(baseFare);fares.addView(perKm);fares.addView(minFare);Button saveFare=primary("Guardar tarifas");fares.addView(saveFare);root.addView(fares);addBottomNav("Dashboard","Choferes","Viajes","Pagos","Más");savePay.setOnClickListener(v->saveBilling());saveFare.setOnClickListener(v->saveFare());refreshAll();startRealtime();startPoller();}

    void addBottomNav(String... labels){LinearLayout n=new LinearLayout(this);n.setGravity(Gravity.CENTER);n.setPadding(0,dp(8),0,0);for(String s:labels){TextView t=txt(s,10,MUTED,true);t.setGravity(Gravity.CENTER);t.setPadding(dp(1),dp(9),dp(1),dp(9));n.addView(t,new LinearLayout.LayoutParams(0,-2,1));}n.setBackground(shape(PANEL,18,1));root.addView(n);}
    LinearLayout subCard(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(12),dp(10),dp(12),dp(10));c.setBackground(shape(PANEL2,14,0));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(4),0,dp(4));c.setLayoutParams(lp);return c;}
    void refreshAll(){loadMetrics();loadDrivers();loadPayments();loadBilling();loadFares();loadMap();}
    void loadMetrics(){backend.rest("GET","profiles?select=id,role",null,new Backend.Callback(){public void ok(Object v){if(v instanceof JSONArray){JSONArray a=(JSONArray)v;int u=0;for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null&&"usuario".equals(o.optString("role")))u++;}usersMetric.setText(u+"\nUsuarios");}}public void error(String m){}});backend.rest("GET","drivers?select=id,status,is_available",null,new Backend.Callback(){public void ok(Object v){if(v instanceof JSONArray){JSONArray a=(JSONArray)v;int on=0;for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null&&o.optBoolean("is_available"))on++;}driversMetric.setText(a.length()+"\nChoferes · "+on+" online");}}public void error(String m){}});backend.rest("GET","trips?order=requested_at.desc&limit=500&select=id,status,estimated_fare,final_fare,requested_at",null,new Backend.Callback(){public void ok(Object v){if(v instanceof JSONArray){JSONArray a=(JSONArray)v;double gross=0;int done=0;for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null&&"completado".equals(o.optString("status"))){done++;gross+=o.optDouble("final_fare",o.optDouble("estimated_fare",0));}}tripsMetric.setText(a.length()+"\nViajes · "+done+" completados");revenueMetric.setText("S/ "+String.format("%.2f",gross)+"\nFacturado");}}public void error(String m){}});}
    void loadDrivers(){driversBox.removeAllViews();backend.rpc("admin_driver_directory",new JSONObject(),new Backend.Callback(){public void ok(Object v){if(!(v instanceof JSONArray)){driversBox.addView(txt("No hay datos.",14,MUTED,false));return;}JSONArray a=(JSONArray)v;int p=0;for(int i=0;i<a.length();i++){JSONObject d=a.optJSONObject(i);if(d==null||!"pendiente".equals(d.optString("status")))continue;p++;LinearLayout c=subCard();c.addView(txt(d.optString("full_name","Chofer")+"  ·  "+d.optString("plate","Sin placa"),15,Color.WHITE,true));c.addView(txt("DNI: "+d.optString("document_number","—")+"  ·  Licencia: "+d.optString("license_number","—"),12,MUTED,false));LinearLayout r=new LinearLayout(PremiumActivity.this);Button no=action("Rechazar",RED),yes=action("Aprobar",GREEN);r.addView(no,new LinearLayout.LayoutParams(0,dp(48),1));r.addView(yes,new LinearLayout.LayoutParams(0,dp(48),1));c.addView(r);driversBox.addView(c);String id=d.optString("id");yes.setOnClickListener(x->reviewDriver(id,"aprobado"));no.setOnClickListener(x->reviewDriver(id,"rechazado"));}if(p==0)driversBox.addView(txt("No hay choferes pendientes.",14,MUTED,false));}public void error(String m){driversBox.addView(txt("Error: "+m,14,RED,false));}});}
    void reviewDriver(String id,String st){try{backend.rpc("admin_set_driver_status",new JSONObject().put("p_driver_id",id).put("p_status",st),new Backend.Callback(){public void ok(Object v){toast("Chofer "+st);loadDrivers();loadMetrics();}public void error(String m){toast(m);}});}catch(Exception ignored){}}
    void loadPayments(){paymentsBox.removeAllViews();backend.rest("GET","driver_subscription_payments?status=eq.pending&order=submitted_at.asc&limit=40&select=*",null,new Backend.Callback(){public void ok(Object v){if(!(v instanceof JSONArray)){paymentsBox.addView(txt("Sin pagos pendientes.",14,MUTED,false));return;}JSONArray a=(JSONArray)v;if(a.length()==0){paymentsBox.addView(txt("No hay pagos pendientes.",14,MUTED,false));return;}for(int i=0;i<a.length();i++){JSONObject p=a.optJSONObject(i);if(p==null)continue;LinearLayout c=subCard();c.addView(txt(p.optString("plan","weekly").toUpperCase()+"  ·  S/ "+p.optString("amount","0"),15,Color.WHITE,true));c.addView(txt("Operación Yape: "+p.optString("yape_operation","—"),12,MUTED,false));LinearLayout r=new LinearLayout(PremiumActivity.this);Button no=action("Rechazar",RED),yes=action("Aprobar",GREEN);r.addView(no,new LinearLayout.LayoutParams(0,dp(48),1));r.addView(yes,new LinearLayout.LayoutParams(0,dp(48),1));c.addView(r);paymentsBox.addView(c);String id=p.optString("id");yes.setOnClickListener(x->reviewPayment(id,true));no.setOnClickListener(x->reviewPayment(id,false));}}public void error(String m){paymentsBox.addView(txt("Error: "+m,14,RED,false));}});}
    void reviewPayment(String id,boolean approve){try{backend.rpc("admin_review_driver_membership_payment",new JSONObject().put("p_payment_id",id).put("p_approve",approve).put("p_note","Revisado desde CiviMoto Admin Premium"),new Backend.Callback(){public void ok(Object v){toast(approve?"Pago aprobado":"Pago rechazado");loadPayments();}public void error(String m){toast(m);}});}catch(Exception ignored){}}
    void loadBilling(){backend.rest("GET","driver_billing_config?id=eq.true&select=*",null,new Backend.Callback(){public void ok(Object v){JSONObject c=Backend.firstObject(v);if(c!=null){weekly.setText(c.optString("weekly_amount","0"));monthly.setText(c.optString("monthly_amount","0"));yapeName.setText(c.optString("yape_display_name",""));yapeNumber.setText(c.optString("yape_number",""));}}public void error(String m){}});}
    void saveBilling(){try{JSONObject b=new JSONObject().put("weekly_amount",Double.parseDouble(weekly.getText().toString())).put("monthly_amount",Double.parseDouble(monthly.getText().toString())).put("yape_display_name",yapeName.getText().toString().trim()).put("yape_number",yapeNumber.getText().toString().trim());backend.rest("PATCH","driver_billing_config?id=eq.true",b,new Backend.Callback(){public void ok(Object v){toast("Configuración Yape guardada");}public void error(String m){toast(m);}});}catch(Exception e){toast("Revisa los montos");}}
    void loadFares(){backend.rest("GET","fares?active=eq.true&order=created_at.desc&limit=1&select=id,base_fare,per_km,minimum_fare",null,new Backend.Callback(){public void ok(Object v){JSONObject f=Backend.firstObject(v);if(f!=null){baseFare.setText(f.optString("base_fare","3.00"));perKm.setText(f.optString("per_km","1.50"));minFare.setText(f.optString("minimum_fare","5.00"));}}public void error(String m){}});}
    void saveFare(){try{JSONObject b=new JSONObject().put("base_fare",Double.parseDouble(baseFare.getText().toString())).put("per_km",Double.parseDouble(perKm.getText().toString())).put("minimum_fare",Double.parseDouble(minFare.getText().toString())).put("platform_commission_percent",0);backend.rest("PATCH","fares?active=eq.true",b,new Backend.Callback(){public void ok(Object v){toast("Tarifas actualizadas");}public void error(String m){toast(m);}});}catch(Exception e){toast("Revisa las tarifas");}}
    void loadMap(){backend.rest("GET","driver_live_locations?select=driver_id,lat,lng,updated_at",null,new Backend.Callback(){public void ok(Object v){if(v instanceof JSONArray&&map!=null)map.evaluateJavascript("setDrivers("+JSONObject.quote(v.toString())+")",null);}public void error(String m){}});}

    void startRealtime(){realtime=new RealtimeBridge(this,backend,this);WebView w=realtime.start("cm_trips","cm_driver_live_locations","cm_driver_subscription_payments","cm_driver_billing_config","cm_drivers","cm_profiles");w.setVisibility(View.INVISIBLE);root.addView(w,new LinearLayout.LayoutParams(1,1));}
    void startPoller(){poller=new Runnable(){public void run(){if(backend.hasSession()){loadMetrics();loadMap();}handler.postDelayed(this,6000);}};handler.postDelayed(poller,6000);}
    void stopRealtime(){if(realtime!=null)realtime.stop();if(poller!=null)handler.removeCallbacks(poller);}
    public void onRealtime(String table,String payload){connection.setText("● En tiempo real");if(table.contains("live_locations"))loadMap();else if(table.contains("payments"))loadPayments();else if(table.contains("drivers"))loadDrivers();loadMetrics();}
    public void onRealtimeStatus(String s){connection.setText("SUBSCRIBED".equals(s)?"● En tiempo real":"Sincronizando…");}
    WebView createMap(){WebView w=new WebView(this);WebSettings s=w.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);w.setWebViewClient(new WebViewClient());String html="<!doctype html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'><link href='https://unpkg.com/maplibre-gl@5.6.2/dist/maplibre-gl.css' rel='stylesheet'><style>html,body,#m{margin:0;width:100%;height:100%;background:#101216}</style></head><body><div id='m'></div><script src='https://unpkg.com/maplibre-gl@5.6.2/dist/maplibre-gl.js'></script><script>let map=new maplibregl.Map({container:'m',style:'https://tiles.openfreemap.org/styles/liberty',center:[-77.0428,-12.0464],zoom:12.5});let marks=[];function setDrivers(s){marks.forEach(x=>x.remove());marks=[];try{JSON.parse(s).forEach(d=>{marks.push(new maplibregl.Marker({color:'#ffbe00'}).setLngLat([d.lng,d.lat]).addTo(map));});}catch(e){}}</script></body></html>";w.loadDataWithBaseURL("https://admin.civimoto.local/",html,"text/html","UTF-8",null);return w;}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    @Override protected void onDestroy(){super.onDestroy();stopRealtime();}
}
