package pe.civimoto.chofer;

import android.Manifest;
import android.app.Activity;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.location.Location;
import android.location.LocationListener;
import android.location.LocationManager;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.Gravity;
import android.view.View;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.*;
import org.json.JSONArray;
import org.json.JSONObject;
import java.util.HashSet;

public class FlowActivity extends Activity implements RealtimeBridge.Listener {
    private final int GOLD=Color.rgb(255,190,0),GOLD2=Color.rgb(255,220,90),BLACK=Color.rgb(5,6,8),PANEL=Color.rgb(18,20,24),PANEL2=Color.rgb(29,31,37),MUTED=Color.rgb(176,180,190),RED=Color.rgb(235,65,65),GREEN=Color.rgb(35,190,105);
    private final Handler h=new Handler(Looper.getMainLooper()); private final HashSet<String> rejected=new HashSet<>();
    private Backend backend; private RealtimeBridge realtime; private CiviAlert alerts; private LinearLayout body; private WebView map; private Runnable poller; private LocationManager lm; private LocationListener ll;
    private String offeredTripId,activeTripId,tripStatus=""; private boolean online=false; private double lat=-12.0464,lng=-77.0428; private TextView connection,offerText,tripText;

    int dp(int v){return(int)(v*getResources().getDisplayMetrics().density);} GradientDrawable shape(int c,int r,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));if(stroke>0)g.setStroke(dp(stroke),GOLD);return g;} GradientDrawable gold(){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{GOLD2,GOLD,Color.rgb(255,158,0)});g.setCornerRadius(dp(16));return g;}
    TextView tx(String s,int sp,int c,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(c);if(b)t.setTypeface(null,1);t.setPadding(0,dp(3),0,dp(3));return t;} ImageView logo(int s){ImageView i=new ImageView(this);i.setImageResource(R.drawable.logo_civimoto);i.setScaleType(ImageView.ScaleType.CENTER_CROP);i.setBackground(shape(Color.BLACK,22,1));i.setClipToOutline(true);i.setLayoutParams(new LinearLayout.LayoutParams(dp(s),dp(s)));return i;}
    LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(15),dp(16),dp(15));c.setBackground(shape(PANEL,20,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(7),0,dp(7));c.setLayoutParams(lp);return c;} EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setHintTextColor(MUTED);e.setTextColor(Color.WHITE);e.setSingleLine(true);e.setPadding(dp(14),dp(11),dp(14),dp(11));e.setBackground(shape(PANEL2,14,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(54));lp.setMargins(0,dp(5),0,dp(5));e.setLayoutParams(lp);return e;} Button btn(String s,boolean p){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(15);b.setTypeface(null,1);b.setTextColor(p?Color.BLACK:Color.WHITE);b.setBackground(p?gold():shape(PANEL2,16,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(54));lp.setMargins(0,dp(5),0,dp(5));b.setLayoutParams(lp);return b;}

    @Override public void onCreate(Bundle b){super.onCreate(b);backend=new Backend(this);alerts=new CiviAlert(this);requestPermissionsNeeded();showSplash();h.postDelayed(()->backend.bootstrap(new Backend.Callback(){public void ok(Object v){if(backend.hasSession())backend.resume("chofer",new Backend.Callback(){public void ok(Object x){screenDashboard();}public void error(String m){screenLogin();}});else screenLogin();}public void error(String m){screenLogin();toast("Servidor: "+m);}}),900);}
    void showSplash(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setGravity(Gravity.CENTER);r.setPadding(dp(28),dp(28),dp(28),dp(28));r.setBackgroundColor(BLACK);r.addView(logo(260));TextView n=tx("CiviMoto",48,Color.WHITE,true);n.setGravity(Gravity.CENTER);r.addView(n);TextView t=tx("Chofer · Conduce tu futuro",19,GOLD2,true);t.setGravity(Gravity.CENTER);r.addView(t);setContentView(r);}
    void shell(String title,String subtitle,int step){stopPoller();ScrollView sc=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(14),dp(14),dp(14),dp(70));root.setBackgroundColor(BLACK);sc.addView(root);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.addView(logo(62));LinearLayout ht=new LinearLayout(this);ht.setOrientation(LinearLayout.VERTICAL);ht.setPadding(dp(11),0,0,0);ht.addView(tx(title,25,Color.WHITE,true));ht.addView(tx(subtitle,12,GOLD2,false));head.addView(ht,new LinearLayout.LayoutParams(0,-2,1));TextView badge=tx(step+" / 6",12,GOLD2,true);badge.setPadding(dp(10),dp(7),dp(10),dp(7));badge.setBackground(shape(PANEL2,18,1));head.addView(badge);root.addView(head);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(0,dp(12),0,0);root.addView(body);setContentView(sc);}

    void screenLogin(){alerts.stopOffer();shell("CiviMoto Chofer","Pantalla 1 · Iniciar sesión",1);LinearLayout c=card();c.addView(tx("Hola, chofer",24,Color.WHITE,true));EditText email=input("Correo electrónico"),pass=input("Contraseña");pass.setInputType(0x81);c.addView(email);c.addView(pass);Button login=btn("Iniciar sesión",true),reg=btn("Registrarme como chofer",false);c.addView(login);c.addView(reg);body.addView(c);login.setOnClickListener(v->{login.setEnabled(false);backend.login(email.getText().toString(),pass.getText().toString(),"chofer",new Backend.Callback(){public void ok(Object x){screenDashboard();}public void error(String m){login.setEnabled(true);toast(m);}});});reg.setOnClickListener(v->screenRegister());}
    void screenRegister(){alerts.stopOffer();shell("Registro de chofer","Pantalla 2 · Crear cuenta",2);LinearLayout c=card();EditText name=input("Nombre completo"),email=input("Correo electrónico"),phone=input("Teléfono"),plate=input("Placa del mototaxi"),pass=input("Contraseña (8+ caracteres)");pass.setInputType(0x81);c.addView(name);c.addView(email);c.addView(phone);c.addView(plate);c.addView(pass);Button create=btn("Crear cuenta",true),back=btn("Volver a iniciar sesión",false);c.addView(create);c.addView(back);body.addView(c);create.setOnClickListener(v->{create.setEnabled(false);backend.register(name.getText().toString(),email.getText().toString(),pass.getText().toString(),"chofer",new Backend.Callback(){public void ok(Object x){backend.login(email.getText().toString(),pass.getText().toString(),"chofer",new Backend.Callback(){public void ok(Object y){screenDashboard();toast("Cuenta creada. El administrador debe aprobarla.");}public void error(String m){create.setEnabled(true);toast(m);}});}public void error(String m){create.setEnabled(true);toast(m);}});});back.setOnClickListener(v->screenLogin());}

    void screenDashboard(){alerts.stopOffer();shell("Panel del chofer","Pantalla 3 · En línea y mapa",3);connection=tx("Conectando con central…",12,MUTED,false);body.addView(connection);LinearLayout st=card();Switch sw=new Switch(this);sw.setTextColor(Color.WHITE);sw.setText("Fuera de línea");st.addView(tx("Disponibilidad",21,Color.WHITE,true));st.addView(sw);TextView account=tx("Validando tu cuenta…",13,MUTED,false);st.addView(account);body.addView(st);map=createMap();body.addView(map,new LinearLayout.LayoutParams(-1,dp(310)));LinearLayout actions=card();Button services=btn("Ver solicitudes disponibles",true),earn=btn("Ganancias y membresía",false),logout=btn("Cerrar sesión",false);actions.addView(services);actions.addView(earn);actions.addView(logout);body.addView(actions);sw.setOnCheckedChangeListener((v,on)->{online=on;sw.setText(on?"En línea":"Fuera de línea");setAvailability(on);if(on){freshLocation();startRealtime();startPoller();}});services.setOnClickListener(v->screenOffer());earn.setOnClickListener(v->screenEarnings());logout.setOnClickListener(v->{setAvailability(false);backend.logout();stopAll();screenLogin();});freshLocation();backend.rest("GET","drivers?id=eq."+backend.getUserId()+"&select=status,is_available,rating",null,new Backend.Callback(){public void ok(Object x){JSONObject d=Backend.firstObject(x);if(d!=null){String status=d.optString("status","pendiente");online=d.optBoolean("is_available",false);sw.setChecked(online);account.setText("Estado: "+status+" · ★ "+d.optString("rating","5.0"));if(!"aprobado".equals(status)){sw.setEnabled(false);account.setText("Cuenta "+status+". Espera aprobación del administrador.");}}}public void error(String m){account.setText("No se pudo validar la cuenta.");}});loadActiveTripThenRoute();}

    void loadActiveTripThenRoute(){backend.rest("GET","trips?driver_id=eq."+backend.getUserId()+"&status=in.(aceptado,chofer_en_camino,chofer_llego,en_viaje)&order=accepted_at.desc&limit=1&select=*",null,new Backend.Callback(){public void ok(Object x){JSONObject t=Backend.firstObject(x);if(t!=null){activeTripId=t.optString("id");tripStatus=t.optString("status");h.postDelayed(()->screenTrip(),250);}}public void error(String m){}});}

    void screenOffer(){shell("Solicitudes disponibles","Pantalla 4 · Aceptar o rechazar",4);connection=tx("Buscando viajes cercanos…",12,MUTED,false);body.addView(connection);map=createMap();body.addView(map,new LinearLayout.LayoutParams(-1,dp(300)));LinearLayout c=card();offerText=tx("Buscando una solicitud…",16,Color.WHITE,true);c.addView(offerText);Button accept=btn("Aceptar viaje",true),reject=btn("Rechazar",false),back=btn("Volver al panel",false);c.addView(accept);c.addView(reject);c.addView(back);body.addView(c);accept.setEnabled(false);reject.setEnabled(false);accept.setOnClickListener(v->{if(offeredTripId==null)return;alerts.stopOffer();try{backend.rpc("accept_civimoto_trip",new JSONObject().put("p_trip_id",offeredTripId),new Backend.Callback(){public void ok(Object x){JSONObject t=Backend.firstObject(x);if(t!=null){activeTripId=t.optString("id");tripStatus=t.optString("status");offeredTripId=null;transition("chofer_en_camino",()->screenTrip());}}public void error(String m){toast(m);loadOffers(accept,reject);}});}catch(Exception ignored){}});reject.setOnClickListener(v->{if(offeredTripId!=null)rejected.add(offeredTripId);alerts.stopOffer();offeredTripId=null;offerText.setText("Solicitud rechazada. Buscando otra…");accept.setEnabled(false);reject.setEnabled(false);h.postDelayed(()->loadOffers(accept,reject),800);});back.setOnClickListener(v->{alerts.stopOffer();screenDashboard();});freshLocation();online=true;startRealtime();loadOffers(accept,reject);poller=new Runnable(){public void run(){if(activeTripId==null)loadOffers(accept,reject);h.postDelayed(this,3500);}};h.postDelayed(poller,3500);}

    void loadOffers(Button accept,Button reject){if(!online||activeTripId!=null)return;try{backend.rpc("driver_available_trips",new JSONObject().put("p_radius_km",7),new Backend.Callback(){public void ok(Object x){JSONObject t=Backend.firstObject(x);if(t==null||rejected.contains(t.optString("id"))){offeredTripId=null;offerText.setText("No hay solicitudes nuevas cerca.");accept.setEnabled(false);reject.setEnabled(false);alerts.stopOffer();return;}String id=t.optString("id");boolean fresh=!id.equals(offeredTripId);offeredTripId=id;offerText.setText("Origen: "+t.optString("origin_address","—")+"\nDestino: "+t.optString("destination_address","—")+"\nDistancia: "+t.optString("estimated_distance_km","—")+" km\nTarifa: S/ "+t.optString("estimated_fare","—")+" · "+t.optString("payment_method","efectivo").toUpperCase());accept.setEnabled(true);reject.setEnabled(true);if(map!=null)map.evaluateJavascript("showOffer("+t.optDouble("origin_lng")+","+t.optDouble("origin_lat")+","+t.optDouble("destination_lng")+","+t.optDouble("destination_lat")+")",null);if(fresh)alerts.startOffer("Nuevo viaje CiviMoto","Tienes una solicitud. Acepta o rechaza para detener la alerta.");}public void error(String m){connection.setText("Reintentando…");}});}catch(Exception ignored){}}

    void screenTrip(){alerts.stopOffer();shell("Viaje en curso","Pantalla 5 · Recoger, iniciar y finalizar",5);connection=tx("Sincronizando viaje…",12,MUTED,false);body.addView(connection);map=createMap();body.addView(map,new LinearLayout.LayoutParams(-1,dp(300)));LinearLayout c=card();tripText=tx("Cargando viaje…",16,Color.WHITE,true);c.addView(tripText);Button arrived=btn("Llegué al origen",false),start=btn("Iniciar viaje",true),finish=btn("Finalizar viaje",true),earn=btn("Ganancias y membresía",false);c.addView(arrived);c.addView(start);c.addView(finish);c.addView(earn);body.addView(c);arrived.setOnClickListener(v->transition("chofer_llego",this::loadTrip));start.setOnClickListener(v->transition("en_viaje",this::loadTrip));finish.setOnClickListener(v->transition("completado",()->{alerts.event("Viaje finalizado","Servicio completado correctamente",6204);activeTripId=null;screenEarnings();}));earn.setOnClickListener(v->screenEarnings());freshLocation();startRealtime();startPoller();loadTrip();}
    void loadTrip(){if(activeTripId==null){screenDashboard();return;}backend.rest("GET","trips?id=eq."+activeTripId+"&select=*",null,new Backend.Callback(){public void ok(Object x){JSONObject t=Backend.firstObject(x);if(t==null)return;tripStatus=t.optString("status");if(tripText!=null)tripText.setText("Estado: "+friendly(tripStatus)+"\nOrigen: "+t.optString("origin_address","—")+"\nDestino: "+t.optString("destination_address","—")+"\nTarifa: S/ "+t.optString("estimated_fare","—")+" · "+t.optString("payment_method","efectivo").toUpperCase());if(map!=null)map.evaluateJavascript("showOffer("+t.optDouble("origin_lng")+","+t.optDouble("origin_lat")+","+t.optDouble("destination_lng")+","+t.optDouble("destination_lat")+")",null);if("cancelado".equals(tripStatus)||"completado".equals(tripStatus)){activeTripId=null;screenEarnings();}}public void error(String m){}});}
    void transition(String target,Runnable after){if(activeTripId==null)return;try{backend.rpc("driver_transition_trip",new JSONObject().put("p_trip_id",activeTripId).put("p_target_status",target),new Backend.Callback(){public void ok(Object x){tripStatus=target;if("chofer_llego".equals(target))alerts.event("Llegaste al origen","Avisa al pasajero que ya estás esperando",6201);if("en_viaje".equals(target))alerts.event("Viaje iniciado","Ruta activa en CiviMoto",6202);after.run();}public void error(String m){toast(m);}});}catch(Exception ignored){}}

    void screenEarnings(){alerts.stopOffer();shell("Ganancias y membresía","Pantalla 6 · Resumen y pago a CiviMoto",6);LinearLayout c=card();c.addView(tx("Mis ganancias",22,Color.WHITE,true));TextView earnings=tx("Cargando…",17,GOLD2,true);c.addView(earnings);body.addView(c);LinearLayout b=card();b.addView(tx("Membresía CiviMoto",21,Color.WHITE,true));TextView config=tx("Cargando configuración…",14,MUTED,false);b.addView(config);EditText op=input("Número de operación Yape");b.addView(op);Button weekly=btn("Enviar pago semanal",false),monthly=btn("Enviar pago mensual",true),home=btn("Volver al panel",false);b.addView(weekly);b.addView(monthly);b.addView(home);body.addView(b);home.setOnClickListener(v->screenDashboard());weekly.setOnClickListener(v->submitPayment("weekly",op));monthly.setOnClickListener(v->submitPayment("monthly",op));backend.rest("GET","trips?driver_id=eq."+backend.getUserId()+"&status=eq.completado&order=completed_at.desc&limit=100&select=final_fare,estimated_fare",null,new Backend.Callback(){public void ok(Object x){double sum=0;int n=0;if(x instanceof JSONArray){JSONArray a=(JSONArray)x;n=a.length();for(int i=0;i<a.length();i++){JSONObject t=a.optJSONObject(i);if(t!=null)sum+=t.optDouble("final_fare",t.optDouble("estimated_fare",0));}}earnings.setText("Total reciente: S/ "+String.format("%.2f",sum)+" · "+n+" viajes");}public void error(String m){earnings.setText("No se pudo cargar ganancias.");}});backend.rest("GET","driver_billing_config?id=eq.true&select=weekly_amount,monthly_amount,yape_display_name,yape_number",null,new Backend.Callback(){public void ok(Object x){JSONObject d=Backend.firstObject(x);if(d!=null)config.setText("Semanal: S/ "+d.optString("weekly_amount","—")+" · Mensual: S/ "+d.optString("monthly_amount","—")+"\nYape: "+d.optString("yape_number","—")+" "+d.optString("yape_display_name",""));}public void error(String m){}});}
    void submitPayment(String plan,EditText op){String value=op.getText().toString().trim();if(value.length()<3){toast("Ingresa el número de operación Yape.");return;}try{backend.rpc("submit_driver_membership_payment",new JSONObject().put("p_plan",plan).put("p_yape_operation",value).put("p_receipt_url",JSONObject.NULL),new Backend.Callback(){public void ok(Object x){alerts.event("Pago enviado","El administrador revisará tu pago",6301);op.setText("");}public void error(String m){toast(m);}});}catch(Exception ignored){}}

    void setAvailability(boolean on){try{backend.rpc("driver_set_availability",new JSONObject().put("p_available",on).put("p_lat",lat).put("p_lng",lng),new Backend.Callback(){public void ok(Object x){online=on;}public void error(String m){online=false;toast(m);}});}catch(Exception ignored){}}
    void startRealtime(){stopRealtime();realtime=new RealtimeBridge(this,backend,this);WebView w=realtime.start("cm_trips","cm_driver_notifications","cm_driver_subscription_payments");w.setVisibility(View.INVISIBLE);body.addView(w,new LinearLayout.LayoutParams(1,1));}
    void startPoller(){stopPoller();poller=new Runnable(){public void run(){if(activeTripId!=null)loadTrip();h.postDelayed(this,4000);}};h.postDelayed(poller,4000);} void stopPoller(){if(poller!=null){h.removeCallbacks(poller);poller=null;}} void stopRealtime(){if(realtime!=null){realtime.stop();realtime=null;}} public void onRealtime(String table,String payload){if(connection!=null)connection.setText("● En tiempo real");if(activeTripId!=null)loadTrip();} public void onRealtimeStatus(String s){if(connection!=null)connection.setText("SUBSCRIBED".equals(s)?"● En tiempo real":"Sincronizando…");}

    void requestPermissionsNeeded(){if(android.os.Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},30);if(android.os.Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},31);}
    void freshLocation(){try{lm=(LocationManager)getSystemService(LOCATION_SERVICE);if(android.os.Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return;Location g=lm.getLastKnownLocation(LocationManager.GPS_PROVIDER),n=lm.getLastKnownLocation(LocationManager.NETWORK_PROVIDER),best=g!=null?g:n;if(best!=null)applyLocation(best);if(ll==null)ll=new LocationListener(){public void onLocationChanged(Location l){applyLocation(l);}public void onStatusChanged(String p,int s,Bundle b){}public void onProviderEnabled(String p){}public void onProviderDisabled(String p){}};try{lm.requestLocationUpdates(LocationManager.GPS_PROVIDER,3000,3,ll);}catch(Exception ignored){}try{lm.requestLocationUpdates(LocationManager.NETWORK_PROVIDER,4000,5,ll);}catch(Exception ignored){}}catch(Exception ignored){}}
    void applyLocation(Location l){lat=l.getLatitude();lng=l.getLongitude();if(map!=null)map.evaluateJavascript("setMe("+lng+","+lat+")",null);if(backend.hasSession()&&(online||activeTripId!=null)){try{backend.rpc("driver_update_live_location",new JSONObject().put("p_lat",lat).put("p_lng",lng).put("p_heading",l.hasBearing()?l.getBearing():JSONObject.NULL).put("p_speed_kmh",l.hasSpeed()?l.getSpeed()*3.6:JSONObject.NULL).put("p_trip_id",activeTripId==null?JSONObject.NULL:activeTripId),new Backend.Callback(){public void ok(Object x){}public void error(String m){}});}catch(Exception ignored){}}}
    WebView createMap(){WebView w=new WebView(this);WebSettings s=w.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);w.setWebViewClient(new WebViewClient());String html="<!doctype html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'><link href='https://unpkg.com/maplibre-gl@5.6.2/dist/maplibre-gl.css' rel='stylesheet'><style>html,body,#m{margin:0;width:100%;height:100%;background:#101216}</style></head><body><div id='m'></div><script src='https://unpkg.com/maplibre-gl@5.6.2/dist/maplibre-gl.js'></script><script>let map=new maplibregl.Map({container:'m',style:'https://tiles.openfreemap.org/styles/liberty',center:[-77.0428,-12.0464],zoom:13});let me,a,b;function setMe(x,y){if(me)me.remove();me=new maplibregl.Marker({color:'#ffbe00'}).setLngLat([x,y]).addTo(map);map.flyTo({center:[x,y],zoom:16});}function showOffer(x1,y1,x2,y2){if(a)a.remove();if(b)b.remove();a=new maplibregl.Marker({color:'#23be69'}).setLngLat([x1,y1]).addTo(map);b=new maplibregl.Marker({color:'#ef4040'}).setLngLat([x2,y2]).addTo(map);map.fitBounds([[x1,y1],[x2,y2]],{padding:45});}</script></body></html>";w.loadDataWithBaseURL("https://driver.civimoto.local/",html,"text/html","UTF-8",null);h.postDelayed(()->{if(map!=null)map.evaluateJavascript("setMe("+lng+","+lat+")",null);},1000);return w;}
    String friendly(String s){if("aceptado".equals(s))return"Aceptado";if("chofer_en_camino".equals(s))return"En camino al pasajero";if("chofer_llego".equals(s))return"Llegaste al origen";if("en_viaje".equals(s))return"Viaje en curso";if("completado".equals(s))return"Completado";if("cancelado".equals(s))return"Cancelado";return s;}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();} void stopAll(){alerts.stopOffer();stopRealtime();stopPoller();try{if(lm!=null&&ll!=null)lm.removeUpdates(ll);}catch(Exception ignored){}} @Override protected void onDestroy(){super.onDestroy();stopAll();if(alerts!=null)alerts.release();}
}
