package pe.civimoto.chofer;

import android.Manifest;
import android.app.Activity;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.location.Location;
import android.location.LocationListener;
import android.location.LocationManager;
import android.os.Build;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.Gravity;
import android.view.View;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.*;
import org.json.JSONArray;
import org.json.JSONObject;
import java.util.ArrayList;

public class PremiumActivity extends Activity implements RealtimeBridge.Listener {
    private final int GOLD=Color.rgb(255,190,0), GOLD2=Color.rgb(255,215,70), BLACK=Color.rgb(7,8,10), PANEL=Color.rgb(18,20,24), PANEL2=Color.rgb(27,29,34), MUTED=Color.rgb(170,174,184), RED=Color.rgb(235,64,64), GREEN=Color.rgb(38,190,105);
    private final Handler handler=new Handler(Looper.getMainLooper());
    private Backend backend; private RealtimeBridge realtime; private CiviAlert alerts; private LinearLayout root; private WebView map;
    private TextView connection,state,offerText,tripText,earningsText,billingText; private Switch onlineSwitch;
    private Button acceptBtn,rejectBtn,arrivedBtn,startBtn,finishBtn; private EditText yapeOperation;
    private String offeredTripId,activeTripId,tripStatus,ringingTripId,rejectedTripId; private long rejectedUntil=0L;
    private boolean online=false; private double lat=-12.0464,lng=-77.0428;
    private LocationManager lm; private LocationListener ll; private Runnable poller;

    int dp(int v){return (int)(v*getResources().getDisplayMetrics().density);}
    GradientDrawable shape(int c,int r,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));if(stroke>0)g.setStroke(dp(stroke),GOLD);return g;}
    GradientDrawable gold(){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{GOLD2,GOLD,Color.rgb(255,155,0)});g.setCornerRadius(dp(16));return g;}
    TextView txt(String s,int sp,int c,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(c);if(b)t.setTypeface(null,1);t.setPadding(0,dp(3),0,dp(3));return t;}
    ImageView logo(int s){ImageView i=new ImageView(this);i.setImageResource(R.drawable.logo_civimoto);i.setScaleType(ImageView.ScaleType.CENTER_CROP);i.setBackground(shape(Color.BLACK,24,1));i.setClipToOutline(true);i.setLayoutParams(new LinearLayout.LayoutParams(dp(s),dp(s)));return i;}
    LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(15),dp(16),dp(15));c.setBackground(shape(PANEL,20,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(7),0,dp(7));c.setLayoutParams(lp);return c;}
    Button primary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.BLACK);b.setTypeface(null,1);b.setTextSize(15);b.setBackground(gold());LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(54));lp.setMargins(0,dp(5),0,dp(5));b.setLayoutParams(lp);return b;}
    Button dark(String s){Button b=primary(s);b.setTextColor(Color.WHITE);b.setBackground(shape(PANEL2,16,1));return b;}
    Button red(String s){Button b=primary(s);b.setTextColor(Color.WHITE);b.setBackground(shape(RED,16,0));return b;}
    Button green(String s){Button b=primary(s);b.setTextColor(Color.WHITE);b.setBackground(shape(GREEN,16,0));return b;}
    EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setHintTextColor(MUTED);e.setTextColor(Color.WHITE);e.setSingleLine(true);e.setPadding(dp(14),dp(12),dp(14),dp(12));e.setBackground(shape(PANEL2,14,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(54));lp.setMargins(0,dp(5),0,dp(5));e.setLayoutParams(lp);return e;}
    TextView chip(String s){TextView t=txt(s,12,GOLD2,true);t.setGravity(Gravity.CENTER);t.setPadding(dp(12),dp(8),dp(12),dp(8));t.setBackground(shape(PANEL2,20,1));return t;}

    @Override public void onCreate(Bundle b){super.onCreate(b);backend=new Backend(this);alerts=new CiviAlert(this);requestPermissionsNeeded();showSplash();handler.postDelayed(()->backend.bootstrap(new Backend.Callback(){public void ok(Object v){if(backend.hasSession())backend.resume("chofer",new Backend.Callback(){public void ok(Object x){showHome();}public void error(String m){showLogin();}});else showLogin();}public void error(String m){showLogin();toast("Servidor: "+m);}}),900);}

    void showSplash(){LinearLayout s=new LinearLayout(this);s.setOrientation(LinearLayout.VERTICAL);s.setGravity(Gravity.CENTER);s.setPadding(dp(24),dp(28),dp(24),dp(28));s.setBackgroundColor(BLACK);s.addView(logo(286));TextView n=txt("CiviMoto",48,Color.WHITE,true);n.setGravity(Gravity.CENTER);s.addView(n);TextView tag=txt("Chofer · Conduce tu futuro",19,GOLD2,true);tag.setGravity(Gravity.CENTER);s.addView(tag);TextView p=chip("RECIBE SERVICIOS  •  GPS  •  ALERTAS");LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2);lp.setMargins(0,dp(22),0,0);p.setLayoutParams(lp);s.addView(p);setContentView(s);}

    void showLogin(){alerts.stopOffer();ScrollView sc=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(22),dp(24),dp(22),dp(38));r.setBackgroundColor(BLACK);sc.addView(r);setContentView(sc);LinearLayout brand=new LinearLayout(this);brand.setOrientation(LinearLayout.VERTICAL);brand.setGravity(Gravity.CENTER);brand.addView(logo(160));TextView title=txt("CiviMoto",38,Color.WHITE,true);title.setGravity(Gravity.CENTER);brand.addView(title);TextView sub=txt("Hola, Chofer · Tu esfuerzo, más oportunidades",15,GOLD2,true);sub.setGravity(Gravity.CENTER);brand.addView(sub);r.addView(brand);LinearLayout c=card();c.addView(txt("Cuenta del chofer",21,Color.WHITE,true));EditText name=input("Nombre completo"),email=input("Correo electrónico"),pass=input("Contraseña");pass.setInputType(0x81);c.addView(name);c.addView(email);c.addView(pass);Button login=primary("Iniciar sesión"),reg=dark("Registrarme como chofer");c.addView(login);c.addView(reg);r.addView(c);LinearLayout f=card();f.addView(txt("Alertas CiviMoto",18,Color.WHITE,true));f.addView(txt("Cuando estés En línea, una solicitud hará sonar el teléfono repetidamente hasta que aceptes o rechaces.",14,MUTED,false));r.addView(f);login.setOnClickListener(v->{login.setEnabled(false);backend.login(email.getText().toString(),pass.getText().toString(),"chofer",new Backend.Callback(){public void ok(Object x){showHome();}public void error(String m){login.setEnabled(true);toast(m);}});});reg.setOnClickListener(v->{reg.setEnabled(false);backend.register(name.getText().toString(),email.getText().toString(),pass.getText().toString(),"chofer",new Backend.Callback(){public void ok(Object x){toast("Cuenta creada. El administrador debe aprobarla.");backend.login(email.getText().toString(),pass.getText().toString(),"chofer",new Backend.Callback(){public void ok(Object y){showHome();}public void error(String m){reg.setEnabled(true);toast(m);}});}public void error(String m){reg.setEnabled(true);toast(m);}});});}

    void showHome(){ScrollView sc=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(14),dp(14),dp(14),dp(90));root.setBackgroundColor(BLACK);sc.addView(root);setContentView(sc);LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.addView(logo(64));LinearLayout ht=new LinearLayout(this);ht.setOrientation(LinearLayout.VERTICAL);ht.setPadding(dp(11),0,0,0);ht.addView(txt("CiviMoto Chofer",26,Color.WHITE,true));connection=txt("Conectando en tiempo real…",12,MUTED,false);ht.addView(connection);h.addView(ht,new LinearLayout.LayoutParams(0,-2,1));Button out=dark("Salir");out.setLayoutParams(new LinearLayout.LayoutParams(dp(82),dp(48)));h.addView(out);root.addView(h);out.setOnClickListener(v->{alerts.stopOffer();setAvailability(false);backend.logout();stopRealtime();showLogin();});
        LinearLayout stat=card();stat.addView(txt("En línea / Fuera de línea",20,Color.WHITE,true));onlineSwitch=new Switch(this);onlineSwitch.setTextColor(Color.WHITE);onlineSwitch.setText("Fuera de línea");stat.addView(onlineSwitch);state=txt("Activa el modo En línea para recibir viajes.",14,MUTED,false);stat.addView(state);root.addView(stat);
        map=createMap();root.addView(map,new LinearLayout.LayoutParams(-1,dp(320)));
        LinearLayout offer=card();offer.addView(txt("Nuevo servicio",20,Color.WHITE,true));offerText=txt("No hay solicitudes cercanas.",14,MUTED,false);offer.addView(offerText);LinearLayout row=new LinearLayout(this);rejectBtn=red("Rechazar");acceptBtn=green("Aceptar");row.addView(rejectBtn,new LinearLayout.LayoutParams(0,dp(54),1));row.addView(acceptBtn,new LinearLayout.LayoutParams(0,dp(54),1));offer.addView(row);root.addView(offer);
        LinearLayout trip=card();trip.addView(txt("Viaje en curso",20,Color.WHITE,true));tripText=txt("Sin viaje activo.",14,MUTED,false);trip.addView(tripText);arrivedBtn=dark("Llegué al origen");startBtn=primary("Iniciar viaje");finishBtn=primary("Finalizar viaje");trip.addView(arrivedBtn);trip.addView(startBtn);trip.addView(finishBtn);root.addView(trip);
        LinearLayout gain=card();gain.addView(txt("Mis ganancias",20,Color.WHITE,true));earningsText=txt("Cargando resumen…",16,GOLD2,true);gain.addView(earningsText);root.addView(gain);
        LinearLayout bill=card();bill.addView(txt("Pago al administrador",20,Color.WHITE,true));billingText=txt("Cargando membresía…",14,MUTED,false);bill.addView(billingText);yapeOperation=input("Número de operación Yape");bill.addView(yapeOperation);LinearLayout br=new LinearLayout(this);Button weekly=dark("Pago semanal"),monthly=primary("Pago mensual");br.addView(weekly,new LinearLayout.LayoutParams(0,dp(54),1));br.addView(monthly,new LinearLayout.LayoutParams(0,dp(54),1));bill.addView(br);root.addView(bill);
        acceptBtn.setEnabled(false);rejectBtn.setEnabled(false);arrivedBtn.setEnabled(false);startBtn.setEnabled(false);finishBtn.setEnabled(false);onlineSwitch.setOnCheckedChangeListener((v,on)->{if(on){freshLocation();setAvailability(true);}else{alerts.stopOffer();setAvailability(false);}});acceptBtn.setOnClickListener(v->acceptTrip());rejectBtn.setOnClickListener(v->rejectOffer());arrivedBtn.setOnClickListener(v->transition("chofer_llego"));startBtn.setOnClickListener(v->transition("en_viaje"));finishBtn.setOnClickListener(v->transition("completado"));weekly.setOnClickListener(v->submitPayment("weekly"));monthly.setOnClickListener(v->submitPayment("monthly"));freshLocation();loadDriver();loadActiveTrip();loadBilling();loadEarnings();startRealtime();startPoller();}

    void loadDriver(){backend.rest("GET","drivers?id=eq."+backend.getUserId()+"&select=status,is_available,rating",null,new Backend.Callback(){public void ok(Object v){JSONObject d=Backend.firstObject(v);if(d==null)return;String s=d.optString("status","pendiente");online=d.optBoolean("is_available",false);onlineSwitch.setChecked(online);onlineSwitch.setText(online?"En línea":"Fuera de línea");if(!"aprobado".equals(s)){onlineSwitch.setEnabled(false);state.setText("Cuenta "+s+". El administrador debe aprobarla.");}else state.setText(online?"Disponible para recibir servicios":"Fuera de línea");}public void error(String m){state.setText("No se pudo validar tu cuenta.");}});}
    void setAvailability(boolean on){try{backend.rpc("driver_set_availability",new JSONObject().put("p_available",on).put("p_lat",lat).put("p_lng",lng),new Backend.Callback(){public void ok(Object v){online=on;onlineSwitch.setText(on?"En línea":"Fuera de línea");state.setText(on?"GPS activo · alertas activas":"Fuera de línea");if(on)loadOffers();else alerts.stopOffer();}public void error(String m){online=false;onlineSwitch.setChecked(false);alerts.stopOffer();toast(m);}});}catch(Exception ignored){}}
    void loadOffers(){if(!online||activeTripId!=null){alerts.stopOffer();return;}try{backend.rpc("driver_available_trips",new JSONObject().put("p_radius_km",7),new Backend.Callback(){public void ok(Object v){JSONObject t=Backend.firstObject(v);if(t==null){clearOffer("No hay solicitudes cercanas.");return;}String id=t.optString("id");if(id.equals(rejectedTripId)&&System.currentTimeMillis()<rejectedUntil){clearOffer("Servicio rechazado. Buscando otro…");return;}offeredTripId=id;offerText.setText("Origen: "+t.optString("origin_address","—")+"\nDestino: "+t.optString("destination_address","—")+"\nDistancia: "+t.optString("estimated_distance_km","—")+" km  ·  Tarifa S/ "+t.optString("estimated_fare","—")+"\nPago: "+t.optString("payment_method","efectivo").toUpperCase());acceptBtn.setEnabled(true);rejectBtn.setEnabled(true);if(!id.equals(ringingTripId)){ringingTripId=id;alerts.startOffer("¡Nuevo viaje disponible!","Origen: "+t.optString("origin_address","—")+" · S/ "+t.optString("estimated_fare","—"));}if(map!=null)map.evaluateJavascript("showOffer("+t.optDouble("origin_lng")+","+t.optDouble("origin_lat")+","+t.optDouble("destination_lng")+","+t.optDouble("destination_lat")+")",null);}public void error(String m){connection.setText("Sincronizando…");}});}catch(Exception ignored){}}
    void clearOffer(String msg){offeredTripId=null;ringingTripId=null;alerts.stopOffer();if(offerText!=null)offerText.setText(msg);if(acceptBtn!=null)acceptBtn.setEnabled(false);if(rejectBtn!=null)rejectBtn.setEnabled(false);}
    void rejectOffer(){if(offeredTripId!=null){rejectedTripId=offeredTripId;rejectedUntil=System.currentTimeMillis()+60000L;}clearOffer("Servicio rechazado. Buscando otro…");}
    void acceptTrip(){if(offeredTripId==null)return;alerts.stopOffer();ringingTripId=null;acceptBtn.setEnabled(false);try{backend.rpc("accept_civimoto_trip",new JSONObject().put("p_trip_id",offeredTripId),new Backend.Callback(){public void ok(Object v){JSONObject t=Backend.firstObject(v);if(t!=null){activeTripId=t.optString("id");offeredTripId=null;alerts.event("Viaje aceptado","Ve al punto de origen del pasajero.",4202);renderTrip(t);transition("chofer_en_camino");}}public void error(String m){toast(m);loadOffers();}});}catch(Exception ignored){}}
    void loadActiveTrip(){backend.rest("GET","trips?driver_id=eq."+backend.getUserId()+"&status=in.(aceptado,chofer_en_camino,chofer_llego,en_viaje)&order=accepted_at.desc&limit=1&select=*",null,new Backend.Callback(){public void ok(Object v){JSONObject t=Backend.firstObject(v);if(t!=null){alerts.stopOffer();activeTripId=t.optString("id");renderTrip(t);}else{activeTripId=null;tripText.setText("Sin viaje activo.");setButtons(null);if(online)loadOffers();}}public void error(String m){}});}
    void renderTrip(JSONObject t){tripStatus=t.optString("status");tripText.setText("Estado: "+friendly(tripStatus)+"\nOrigen: "+t.optString("origin_address","—")+"\nDestino: "+t.optString("destination_address","—")+"\nTarifa: S/ "+t.optString("estimated_fare","—")+"  ·  "+t.optString("payment_method","efectivo").toUpperCase());setButtons(tripStatus);if(map!=null)map.evaluateJavascript("showOffer("+t.optDouble("origin_lng")+","+t.optDouble("origin_lat")+","+t.optDouble("destination_lng")+","+t.optDouble("destination_lat")+")",null);if("completado".equals(tripStatus)||"cancelado".equals(tripStatus)){alerts.event("Viaje finalizado","El servicio ya no está activo.",4206);activeTripId=null;setButtons(null);loadEarnings();if(online)loadOffers();}}
    void setButtons(String s){arrivedBtn.setEnabled("chofer_en_camino".equals(s));startBtn.setEnabled("chofer_llego".equals(s));finishBtn.setEnabled("en_viaje".equals(s));}
    void transition(String target){if(activeTripId==null)return;try{backend.rpc("driver_transition_trip",new JSONObject().put("p_trip_id",activeTripId).put("p_target_status",target),new Backend.Callback(){public void ok(Object v){JSONObject t=Backend.firstObject(v);if(t!=null){if("chofer_llego".equals(target))alerts.event("Llegaste al origen","Avisa al pasajero y espera para iniciar.",4203);else if("en_viaje".equals(target))alerts.event("Viaje iniciado","Navega hacia el destino.",4204);else if("completado".equals(target))alerts.event("Viaje completado","Servicio finalizado correctamente.",4205);renderTrip(t);}}public void error(String m){toast(m);}});}catch(Exception ignored){}}
    void loadEarnings(){backend.rest("GET","trips?driver_id=eq."+backend.getUserId()+"&status=eq.completado&order=completed_at.desc&limit=100&select=final_fare,estimated_fare",null,new Backend.Callback(){public void ok(Object v){double sum=0;int n=0;if(v instanceof JSONArray){JSONArray a=(JSONArray)v;n=a.length();for(int i=0;i<a.length();i++){JSONObject t=a.optJSONObject(i);if(t!=null)sum+=t.optDouble("final_fare",t.optDouble("estimated_fare",0));}}earningsText.setText("Total reciente: S/ "+String.format("%.2f",sum)+"  ·  "+n+" viajes");}public void error(String m){earningsText.setText("No se pudo cargar ganancias.");}});}
    void loadBilling(){backend.rest("GET","driver_billing_config?id=eq.true&select=weekly_amount,monthly_amount,yape_display_name,yape_number",null,new Backend.Callback(){public void ok(Object v){JSONObject c=Backend.firstObject(v);if(c!=null)billingText.setText("Semanal: S/ "+c.optString("weekly_amount","—")+"  ·  Mensual: S/ "+c.optString("monthly_amount","—")+"\nYape: "+c.optString("yape_number","Configura el administrador")+"  "+c.optString("yape_display_name",""));}public void error(String m){billingText.setText("No se pudo cargar la membresía.");}});}
    void submitPayment(String plan){String op=yapeOperation.getText().toString().trim();if(op.length()<3){toast("Ingresa el número de operación Yape.");return;}try{backend.rpc("submit_driver_membership_payment",new JSONObject().put("p_plan",plan).put("p_yape_operation",op).put("p_receipt_url",JSONObject.NULL),new Backend.Callback(){public void ok(Object v){alerts.event("Pago enviado","El administrador revisará tu pago.",4210);toast("Pago enviado para aprobación.");yapeOperation.setText("");}public void error(String m){toast(m);}});}catch(Exception ignored){}}

    void startRealtime(){realtime=new RealtimeBridge(this,backend,this);WebView w=realtime.start("cm_trips","cm_driver_subscription_payments","cm_driver_billing_config","cm_driver_notifications");w.setVisibility(View.INVISIBLE);root.addView(w,new LinearLayout.LayoutParams(1,1));}
    void startPoller(){poller=new Runnable(){public void run(){if(backend.hasSession()){loadActiveTrip();if(online&&activeTripId==null)loadOffers();}handler.postDelayed(this,3500);}};handler.postDelayed(poller,2500);}
    void stopRealtime(){alerts.stopOffer();if(realtime!=null)realtime.stop();if(poller!=null)handler.removeCallbacks(poller);try{if(lm!=null&&ll!=null)lm.removeUpdates(ll);}catch(Exception ignored){}}
    public void onRealtime(String table,String payload){connection.setText("● En tiempo real");if(table.contains("trips")){loadActiveTrip();if(online&&activeTripId==null)loadOffers();}if(table.contains("billing")||table.contains("payments"))loadBilling();if(table.contains("notifications"))alerts.event("CiviMoto","Tienes una nueva notificación.",4211);}
    public void onRealtimeStatus(String s){connection.setText("SUBSCRIBED".equals(s)?"● En tiempo real":"Sincronizando…");}

    void requestPermissionsNeeded(){if(Build.VERSION.SDK_INT<23)return;ArrayList<String> p=new ArrayList<>();if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){p.add(Manifest.permission.ACCESS_FINE_LOCATION);p.add(Manifest.permission.ACCESS_COARSE_LOCATION);}if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)p.add(Manifest.permission.POST_NOTIFICATIONS);if(!p.isEmpty())requestPermissions(p.toArray(new String[0]),30);}
    void freshLocation(){try{lm=(LocationManager)getSystemService(LOCATION_SERVICE);if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return;Location last=null;try{last=lm.getLastKnownLocation(LocationManager.GPS_PROVIDER);}catch(Exception ignored){}if(last==null)try{last=lm.getLastKnownLocation(LocationManager.NETWORK_PROVIDER);}catch(Exception ignored){}if(last!=null)applyLocation(last);if(ll==null)ll=new LocationListener(){public void onLocationChanged(Location l){applyLocation(l);}public void onStatusChanged(String p,int s,Bundle b){}public void onProviderEnabled(String p){}public void onProviderDisabled(String p){}};try{lm.requestLocationUpdates(LocationManager.GPS_PROVIDER,3000,3,ll);}catch(Exception ignored){}try{lm.requestLocationUpdates(LocationManager.NETWORK_PROVIDER,4000,4,ll);}catch(Exception ignored){}}catch(Exception ignored){}}
    void applyLocation(Location l){lat=l.getLatitude();lng=l.getLongitude();if(map!=null)map.evaluateJavascript("setMe("+lng+","+lat+")",null);if(backend.hasSession()&&(online||activeTripId!=null)){try{backend.rpc("driver_update_live_location",new JSONObject().put("p_lat",lat).put("p_lng",lng).put("p_heading",l.hasBearing()?l.getBearing():JSONObject.NULL).put("p_speed_kmh",l.hasSpeed()?l.getSpeed()*3.6:JSONObject.NULL).put("p_trip_id",activeTripId==null?JSONObject.NULL:activeTripId),new Backend.Callback(){public void ok(Object v){}public void error(String m){}});}catch(Exception ignored){}}}
    WebView createMap(){WebView w=new WebView(this);WebSettings s=w.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);w.setWebViewClient(new WebViewClient(){@Override public void onPageFinished(WebView v,String u){v.evaluateJavascript("setMe("+lng+","+lat+")",null);}});String html="<!doctype html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'><link href='https://unpkg.com/maplibre-gl@5.6.2/dist/maplibre-gl.css' rel='stylesheet'><style>html,body,#m{margin:0;width:100%;height:100%;background:#101216}</style></head><body><div id='m'></div><script src='https://unpkg.com/maplibre-gl@5.6.2/dist/maplibre-gl.js'></script><script>let map=new maplibregl.Map({container:'m',style:'https://tiles.openfreemap.org/styles/liberty',center:[-77.0428,-12.0464],zoom:13});let me,a,b;function setMe(x,y){if(me)me.remove();me=new maplibregl.Marker({color:'#ffbe00'}).setLngLat([x,y]).addTo(map);map.easeTo({center:[x,y],zoom:16});}function showOffer(x1,y1,x2,y2){if(a)a.remove();if(b)b.remove();a=new maplibregl.Marker({color:'#21be69'}).setLngLat([x1,y1]).addTo(map);b=new maplibregl.Marker({color:'#ef4040'}).setLngLat([x2,y2]).addTo(map);map.fitBounds([[x1,y1],[x2,y2]],{padding:45});}</script></body></html>";w.loadDataWithBaseURL("https://driver.civimoto.local/",html,"text/html","UTF-8",null);return w;}
    String friendly(String s){if("aceptado".equals(s))return"aceptado";if("chofer_en_camino".equals(s))return"en camino al pasajero";if("chofer_llego".equals(s))return"llegaste al origen";if("en_viaje".equals(s))return"en viaje";if("completado".equals(s))return"completado";if("cancelado".equals(s))return"cancelado";return s;}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    @Override protected void onDestroy(){super.onDestroy();stopRealtime();if(alerts!=null)alerts.release();}
}
